/* soapcusdkService.h
   Generated by gSOAP 2.8.0 from cusdk.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapcusdkService_H
#define soapcusdkService_H
#include "soapH.h"
class SOAP_CMAC cusdkService : public soap
{ public:
	/// Constructor
	cusdkService();
	/// Constructor with copy of another engine state
	cusdkService(const struct soap&);
	/// Constructor with engine input+output mode control
	cusdkService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	cusdkService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~cusdkService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Initializer used by constructor
	virtual	void cusdkService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	cusdkService *copy();
	/// Force close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	///

	/// Web service operation 'login' (returns error code or SOAP_OK)
	virtual	int login(cusdk__LoginReq loginReq, cusdk__LoginRsp &loginRsp);

	/// Web service operation 'logout' (returns error code or SOAP_OK)
	virtual	int logout(cusdk__LogoutReq logoutReq, cusdk__LogoutRsp &logoutRsp);

	/// Web service operation 'SubscribePuStatus' (returns error code or SOAP_OK)
	virtual	int SubscribePuStatus(cusdk__SubscribePuStatusReq subscribePuStatusReq, cusdk__SubscribePuStatusRsp &subscribePuStatusRsp);

	/// Web service operation 'UnsubscribePuStatus' (returns error code or SOAP_OK)
	virtual	int UnsubscribePuStatus(cusdk__UnsubscribePuStatusReq unsubscribePuStatusReq, cusdk__UnsubscribePuStatusRsp &unsubscribePuStatusRsp);

	/// Web service operation 'GetNotify' (returns error code or SOAP_OK)
	virtual	int GetNotify(cusdk__GetNotifyReq req, cusdk__GetNotifyRsp &rsp);

	/// Web service operation 'GetCUIList' (returns error code or SOAP_OK)
	virtual	int GetCUIList(cusdk__GetCUIListReq req, cusdk__GetCUIListRsp &rsp);

	/// Web service operation 'SetupStream' (returns error code or SOAP_OK)
	virtual	int SetupStream(cusdk__SetupStreamReq req, cusdk__SetupStreamRsp &rsp);

	/// Web service operation 'PlayStream' (returns error code or SOAP_OK)
	virtual	int PlayStream(cusdk__PlayStreamReq req, cusdk__PlayStreamRsp &rsp);

	/// Web service operation 'StopStream' (returns error code or SOAP_OK)
	virtual	int StopStream(cusdk__StopStreamReq req, cusdk__StopStreamRsp &rsp);

	/// Web service operation 'PtzCtrl' (returns error code or SOAP_OK)
	virtual	int PtzCtrl(cusdk__PtzCtrlReq req, cusdk__PtzCtrlRsp &rsp);

	/// Web service operation 'PtzLock' (returns error code or SOAP_OK)
	virtual	int PtzLock(cusdk__PtzLockReq req, cusdk__PtzLockRsp &rsp);

	/// Web service operation 'PtzUnlock' (returns error code or SOAP_OK)
	virtual	int PtzUnlock(cusdk__PtzUnlockReq req, cusdk__PtzUnlockRsp &rsp);

	/// Web service operation 'SendTransData' (returns error code or SOAP_OK)
	virtual	int SendTransData(cusdk__SendTransDataReq req, cusdk__SendTransDataRsp &rsp);

	/// Web service operation 'GetUserInfo' (returns error code or SOAP_OK)
	virtual	int GetUserInfo(cusdk__GetUserInfoReq req, cusdk__GetUserInfoRsp &rsp);

	/// Web service operation 'GetUserGroupInfo' (returns error code or SOAP_OK)
	virtual	int GetUserGroupInfo(cusdk__GetUserGroupInfoReq req, cusdk__GetUserGroupInfoRsp &rsp);

	/// Web service operation 'GetUserData' (returns error code or SOAP_OK)
	virtual	int GetUserData(cusdk__GetUserDataReq req, cusdk__GetUserDataRsp &rsp);

	/// Web service operation 'SetUserData' (returns error code or SOAP_OK)
	virtual	int SetUserData(cusdk__SetUserDataReq req, cusdk__SetUserDataRsp &rsp);

	/// Web service operation 'GetUserDevGroupByGroup' (returns error code or SOAP_OK)
	virtual	int GetUserDevGroupByGroup(cusdk__GetUserDevGroupByGroupReq req, cusdk__GetUserDevGroupByGroupRsp &rsp);

	/// Web service operation 'GetUserDevByGroup' (returns error code or SOAP_OK)
	virtual	int GetUserDevByGroup(cusdk__GetUserDevByGroupReq req, cusdk__GetUserDevByGroupRsp &rsp);

	/// Web service operation 'GetUserDevGroup' (returns error code or SOAP_OK)
	virtual	int GetUserDevGroup(cusdk__GetUserDevGroupReq req, cusdk__GetUserDevGroupRsp &rsp);

	/// Web service operation 'GetDomainDevGroup' (returns error code or SOAP_OK)
	virtual	int GetDomainDevGroup(cusdk__GetDomainDevGroupReq req, cusdk__GetDomainDevGroupRsp &rsp);

	/// Web service operation 'GetUserDev' (returns error code or SOAP_OK)
	virtual	int GetUserDev(cusdk__GetUserDevReq req, cusdk__GetUserDevRsp &rsp);

	/// Web service operation 'GetUserDevByDomain' (returns error code or SOAP_OK)
	virtual	int GetUserDevByDomain(cusdk__GetDevByDomainReq req, cusdk__GetDevByDomainRsp &rsp);

	/// Web service operation 'GetDeviceGroupDeviceRelations' (returns error code or SOAP_OK)
	virtual	int GetDeviceGroupDeviceRelations(cusdk__GetDeviceGroupDeviceRelationsReq req, cusdk__GetDeviceGroupDeviceRelationsRsp &rsp);

	/// Web service operation 'CreateDeviceGroup' (returns error code or SOAP_OK)
	virtual	int CreateDeviceGroup(cusdk__CreateDeviceGroupReq req, cusdk__CreateDeviceGroupRsp &rsp);

	/// Web service operation 'DelDeviceGroup' (returns error code or SOAP_OK)
	virtual	int DelDeviceGroup(cusdk__DelDeviceGroupReq req, cusdk__DelDeviceGroupRsp &rsp);

	/// Web service operation 'ModifyDeviceGroup' (returns error code or SOAP_OK)
	virtual	int ModifyDeviceGroup(cusdk__ModifyDeviceGroupReq req, cusdk__ModifyDeviceGroupRsp &rsp);

	/// Web service operation 'DeviceGroupAddDevice' (returns error code or SOAP_OK)
	virtual	int DeviceGroupAddDevice(cusdk__DeviceGroupAddDeviceReq req, cusdk__DeviceGroupAddDeviceRsp &rsp);

	/// Web service operation 'DeviceGroupDelDevice' (returns error code or SOAP_OK)
	virtual	int DeviceGroupDelDevice(cusdk__DeviceGroupDelDeviceReq req, cusdk__DeviceGroupDelDeviceRsp &rsp);

	/// Web service operation 'GetUserList' (returns error code or SOAP_OK)
	virtual	int GetUserList(cusdk__GetUserListReq req, cusdk__GetUserListRsp &rsp);

	/// Web service operation 'GetUserGroupList' (returns error code or SOAP_OK)
	virtual	int GetUserGroupList(cusdk__GetUserGroupListReq req, cusdk__GetUserGroupListRsp &rsp);

	/// Web service operation 'CreateUserGroup' (returns error code or SOAP_OK)
	virtual	int CreateUserGroup(cusdk__CreateUserGroupReq req, cusdk__CreateUserGroupRsp &rsp);

	/// Web service operation 'DelUserGroup' (returns error code or SOAP_OK)
	virtual	int DelUserGroup(cusdk__DelUserGroupReq req, cusdk__DelUserGroupRsp &rsp);

	/// Web service operation 'ModifyUserGroup' (returns error code or SOAP_OK)
	virtual	int ModifyUserGroup(cusdk__ModifyUserGroupReq req, cusdk__ModifyUserGroupRsp &rsp);

	/// Web service operation 'CreateUser' (returns error code or SOAP_OK)
	virtual	int CreateUser(cusdk__CreateUserReq req, cusdk__CreateUserRsp &rsp);

	/// Web service operation 'DelUser' (returns error code or SOAP_OK)
	virtual	int DelUser(cusdk__DelUserReq req, cusdk__DelUserRsp &rsp);

	/// Web service operation 'ModifyUser' (returns error code or SOAP_OK)
	virtual	int ModifyUser(cusdk__ModifyUserReq req, cusdk__ModifyUserRsp &rsp);

	/// Web service operation 'UserGetDeviceByGroup' (returns error code or SOAP_OK)
	virtual	int UserGetDeviceByGroup(cusdk__UserGetDeviceByGroupReq req, cusdk__UserGetDeviceByGroupRsp &rsp);

	/// Web service operation 'UserAddDevice' (returns error code or SOAP_OK)
	virtual	int UserAddDevice(cusdk__UserAddDeviceReq req, cusdk__UserAddDeviceRsp &rsp);

	/// Web service operation 'UserDelDevice' (returns error code or SOAP_OK)
	virtual	int UserDelDevice(cusdk__UserDelDeviceReq req, cusdk__UserDelDeviceRsp &rsp);

	/// Web service operation 'UserModifyDevice' (returns error code or SOAP_OK)
	virtual	int UserModifyDevice(cusdk__UserModifyDeviceReq req, cusdk__UserModifyDeviceRsp &rsp);

	/// Web service operation 'GetAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int GetAuthorizationDevice(cusdk__GetAuthorizationDeviceReq req, cusdk__GetAuthorizationDeviceRsp &rsp);

	/// Web service operation 'AddAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int AddAuthorizationDevice(cusdk__AddAuthorizationDeviceReq req, cusdk__AddAuthorizationDeviceRsp &rsp);

	/// Web service operation 'DelAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int DelAuthorizationDevice(cusdk__DelAuthorizationDeviceReq req, cusdk__DelAuthorizationDeviceRsp &rsp);

	/// Web service operation 'ModifyAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int ModifyAuthorizationDevice(cusdk__ModifyAuthorizationDeviceReq req, cusdk__ModifyAuthorizationDeviceRsp &rsp);

	/// Web service operation 'GetDeviceBaseInfo' (returns error code or SOAP_OK)
	virtual	int GetDeviceBaseInfo(cusdk__GetDeviceBaseInfoReq req, cusdk__GetDeviceBaseInfoRsp &rsp);
};
#endif
