/* soapTester.cpp
   Generated by gSOAP 2.8.0 from cusdk.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
/*
   Stand-alone server auto-test code:
   Takes request from standard input or over TCP/IP socket and returns
response to standard output or socket

   Compile:
   cc soapTester.c soapServer.c soapC.c stdsoap2.c

   Command line usage with redirect over stdin/out:
   > ./a.out < SomeTest.req.xml
   > ./a.out 12288 < SomeTest.req.xml
     Note: 12288 = SOAP_XML_INDENT | SOAP_XML_STRICT (see codes in stdsoap2.h)
   Command line usage to start server at port 8080:
   > a.out 12288 8080
*/

#include "soapcusdkService.h"

#ifndef SOAP_DEFMAIN
# define SOAP_DEFMAIN main	/* redefine to use your own main() */
#endif

int SOAP_DEFMAIN(int argc, char **argv)
{
	cusdkService service(argc > 1 ? atoi(argv[1]) : 0);
	if (argc <= 2)
		return service.serve();
	return service.run(atoi(argv[2]));
}


/** Auto-test server operation cusdk__login */
int cusdkService::login(cusdk__LoginReq loginReq, cusdk__LoginRsp &loginRsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__logout */
int cusdkService::logout(cusdk__LogoutReq logoutReq, cusdk__LogoutRsp &logoutRsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SubscribePuStatus */
int cusdkService::SubscribePuStatus(cusdk__SubscribePuStatusReq subscribePuStatusReq, cusdk__SubscribePuStatusRsp &subscribePuStatusRsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UnsubscribePuStatus */
int cusdkService::UnsubscribePuStatus(cusdk__UnsubscribePuStatusReq unsubscribePuStatusReq, cusdk__UnsubscribePuStatusRsp &unsubscribePuStatusRsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetNotify */
int cusdkService::GetNotify(cusdk__GetNotifyReq req, cusdk__GetNotifyRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCUIList */
int cusdkService::GetCUIList(cusdk__GetCUIListReq req, cusdk__GetCUIListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetupStream */
int cusdkService::SetupStream(cusdk__SetupStreamReq req, cusdk__SetupStreamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PlayStream */
int cusdkService::PlayStream(cusdk__PlayStreamReq req, cusdk__PlayStreamRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopStream */
int cusdkService::StopStream(cusdk__StopStreamReq req, cusdk__StopStreamRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PtzCtrl */
int cusdkService::PtzCtrl(cusdk__PtzCtrlReq req, cusdk__PtzCtrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PtzLock */
int cusdkService::PtzLock(cusdk__PtzLockReq req, cusdk__PtzLockRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PtzUnlock */
int cusdkService::PtzUnlock(cusdk__PtzUnlockReq req, cusdk__PtzUnlockRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SendTransData */
int cusdkService::SendTransData(cusdk__SendTransDataReq req, cusdk__SendTransDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserInfo */
int cusdkService::GetUserInfo(cusdk__GetUserInfoReq req, cusdk__GetUserInfoRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserGroupInfo */
int cusdkService::GetUserGroupInfo(cusdk__GetUserGroupInfoReq req, cusdk__GetUserGroupInfoRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserData */
int cusdkService::GetUserData(cusdk__GetUserDataReq req, cusdk__GetUserDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetUserData */
int cusdkService::SetUserData(cusdk__SetUserDataReq req, cusdk__SetUserDataRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevGroupByGroup */
int cusdkService::GetUserDevGroupByGroup(cusdk__GetUserDevGroupByGroupReq req, cusdk__GetUserDevGroupByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevByGroup */
int cusdkService::GetUserDevByGroup(cusdk__GetUserDevByGroupReq req, cusdk__GetUserDevByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevGroup */
int cusdkService::GetUserDevGroup(cusdk__GetUserDevGroupReq req, cusdk__GetUserDevGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDomainDevGroup */
int cusdkService::GetDomainDevGroup(cusdk__GetDomainDevGroupReq req, cusdk__GetDomainDevGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDev */
int cusdkService::GetUserDev(cusdk__GetUserDevReq req, cusdk__GetUserDevRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevByDomain */
int cusdkService::GetUserDevByDomain(cusdk__GetDevByDomainReq req, cusdk__GetDevByDomainRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceGroupDeviceRelations */
int cusdkService::GetDeviceGroupDeviceRelations(cusdk__GetDeviceGroupDeviceRelationsReq req, cusdk__GetDeviceGroupDeviceRelationsRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateDeviceGroup */
int cusdkService::CreateDeviceGroup(cusdk__CreateDeviceGroupReq req, cusdk__CreateDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelDeviceGroup */
int cusdkService::DelDeviceGroup(cusdk__DelDeviceGroupReq req, cusdk__DelDeviceGroupRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyDeviceGroup */
int cusdkService::ModifyDeviceGroup(cusdk__ModifyDeviceGroupReq req, cusdk__ModifyDeviceGroupRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeviceGroupAddDevice */
int cusdkService::DeviceGroupAddDevice(cusdk__DeviceGroupAddDeviceReq req, cusdk__DeviceGroupAddDeviceRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeviceGroupDelDevice */
int cusdkService::DeviceGroupDelDevice(cusdk__DeviceGroupDelDeviceReq req, cusdk__DeviceGroupDelDeviceRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserList */
int cusdkService::GetUserList(cusdk__GetUserListReq req, cusdk__GetUserListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserGroupList */
int cusdkService::GetUserGroupList(cusdk__GetUserGroupListReq req, cusdk__GetUserGroupListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateUserGroup */
int cusdkService::CreateUserGroup(cusdk__CreateUserGroupReq req, cusdk__CreateUserGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelUserGroup */
int cusdkService::DelUserGroup(cusdk__DelUserGroupReq req, cusdk__DelUserGroupRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyUserGroup */
int cusdkService::ModifyUserGroup(cusdk__ModifyUserGroupReq req, cusdk__ModifyUserGroupRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateUser */
int cusdkService::CreateUser(cusdk__CreateUserReq req, cusdk__CreateUserRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelUser */
int cusdkService::DelUser(cusdk__DelUserReq req, cusdk__DelUserRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyUser */
int cusdkService::ModifyUser(cusdk__ModifyUserReq req, cusdk__ModifyUserRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserGetDeviceByGroup */
int cusdkService::UserGetDeviceByGroup(cusdk__UserGetDeviceByGroupReq req, cusdk__UserGetDeviceByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserAddDevice */
int cusdkService::UserAddDevice(cusdk__UserAddDeviceReq req, cusdk__UserAddDeviceRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserDelDevice */
int cusdkService::UserDelDevice(cusdk__UserDelDeviceReq req, cusdk__UserDelDeviceRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserModifyDevice */
int cusdkService::UserModifyDevice(cusdk__UserModifyDeviceReq req, cusdk__UserModifyDeviceRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetAuthorizationDevice */
int cusdkService::GetAuthorizationDevice(cusdk__GetAuthorizationDeviceReq req, cusdk__GetAuthorizationDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__AddAuthorizationDevice */
int cusdkService::AddAuthorizationDevice(cusdk__AddAuthorizationDeviceReq req, cusdk__AddAuthorizationDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelAuthorizationDevice */
int cusdkService::DelAuthorizationDevice(cusdk__DelAuthorizationDeviceReq req, cusdk__DelAuthorizationDeviceRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyAuthorizationDevice */
int cusdkService::ModifyAuthorizationDevice(cusdk__ModifyAuthorizationDeviceReq req, cusdk__ModifyAuthorizationDeviceRsp &rsp)
{	
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceBaseInfo */
int cusdkService::GetDeviceBaseInfo(cusdk__GetDeviceBaseInfoReq req, cusdk__GetDeviceBaseInfoRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}
