#ifndef PUERRORCODE_H
#define PUERRORCODE_H
#define ERROR_BASE  10000
#define ERROR_DISKFULL ERROR_BASE+1 //磁盘满，不能录像
#define ERROR_DISK1_ERROR ERROR_BASE+2 //磁盘分区1发现错误
#define ERROR_DISK2_ERROR ERROR_BASE+3 //
#define ERROR_DISK3_ERROR ERROR_BASE+4 //
#define ERROR_DISK4_ERROR ERROR_BASE+5 //
#define ERROR_DISK5_ERROR ERROR_BASE+6 //
#define ERROR_DISK6_ERROR ERROR_BASE+7 //
#define ERROR_DISK7_ERROR ERROR_BASE+8 //
#define ERROR_DISK8_ERROR ERROR_BASE+9 //
#define ERROR_DISK9_ERROR ERROR_BASE+10 //
#define ERROR_DISK10_ERROR ERROR_BASE+11 //
#define ERROR_DISK11_ERROR ERROR_BASE+12 //
#define ERROR_DISK12_ERROR ERROR_BASE+13 //
#define ERROR_DISK13_ERROR ERROR_BASE+14 //
#define ERROR_DISK14_ERROR ERROR_BASE+15 //
#define ERROR_DISK15_ERROR ERROR_BASE+16
#define ERROR_DISK16_ERROR ERROR_BASE+17 //磁盘分区16发现错误
#define ERROR_NOFUCTIONSUPPORT ERROR_BASE+18 //无硬盘或者硬盘找不到、分区未格式化而禁止该功能
#define ERROR_FILESYSTEM_ERROR ERROR_BASE+20 //由于异常断电等操作造成文件系统损坏，请修复或者重做文件系统，通过现有的操作将重要的录像文件进行备份
#define ERROR_SETRECINFO_ERROR ERROR_BASE+21 //正在录像或预录无法设置录像相关配置参数
#endif
