/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("snmpMPDStats_5_5")) init_snmpMPDStats_5_5();
  if (should_init("usmStats_5_5")) init_usmStats_5_5();
  if (should_init("snmpEngine")) init_snmpEngine();
  if (should_init("usmUser")) init_usmUser();
  if (should_init("snmp_mib_5_5")) init_snmp_mib_5_5();
  if (should_init("system_mib")) init_system_mib();
  if (should_init("sysORTable")) init_sysORTable();
  if (should_init("vacm_vars")) init_vacm_vars();
  if (should_init("setSerialNo")) init_setSerialNo();
  if (should_init("at")) init_at();
  if (should_init("ip")) init_ip();
  if (should_init("tcp")) init_tcp();
  if (should_init("icmp")) init_icmp();
  if (should_init("udp")) init_udp();
  //if (should_init("disk_hw")) init_disk_hw();
  //if (should_init("proc")) init_proc();
  //if (should_init("versioninfo")) init_versioninfo();
  //if (should_init("memory")) init_memory();
  //if (should_init("vmstat")) init_vmstat();
  if (should_init("snmpNotifyTable")) init_snmpNotifyTable();
  if (should_init("snmpNotifyFilterProfileTable")) init_snmpNotifyFilterProfileTable();
  if (should_init("notification_log")) init_notification_log();
  if (should_init("target_counters_5_5")) init_target_counters_5_5();
  if (should_init("snmpTargetAddrEntry")) init_snmpTargetAddrEntry();
  if (should_init("snmpTargetParamsEntry")) init_snmpTargetParamsEntry();  
  if (should_init("hrSWInstalledTable")) init_hrSWInstalledTable();
  if (should_init("hrSWRunTable")) init_hrSWRunTable();


  if (should_init("hr_other")) init_hr_other(); 
  
  if (should_init("vacm_context")) init_vacm_context();
  if (should_init("var_route")) init_var_route();
  if (should_init("tcpTable")) init_tcpTable();
  if (should_init("udpTable")) init_udpTable();
  if (should_init("ip_scalars")) init_ip_scalars();
  if (should_init("snmpNotifyFilterTable")) init_snmpNotifyFilterTable();
  if (should_init("swinst")) init_swinst();
  if (should_init("swrun")) init_swrun();
  if (should_init("hrSWRunPerfTable")) init_hrSWRunPerfTable();
  if (should_init("ifTable")) init_ifTable();
  if (should_init("ifXTable")) init_ifXTable();
  if (should_init("ipAddressTable")) init_ipAddressTable();
  if (should_init("ipAddressPrefixTable")) init_ipAddressPrefixTable();
  if (should_init("ipDefaultRouterTable")) init_ipDefaultRouterTable();
  if (should_init("inetNetToMediaTable")) init_inetNetToMediaTable();
  if (should_init("ipSystemStatsTable")) init_ipSystemStatsTable();
  if (should_init("ipv6ScopeZoneIndexTable")) init_ipv6ScopeZoneIndexTable();
  if (should_init("ipIfStatsTable")) init_ipIfStatsTable();
  if (should_init("ipCidrRouteTable")) init_ipCidrRouteTable();
  if (should_init("inetCidrRouteTable")) init_inetCidrRouteTable();
  if (should_init("tcpConnectionTable")) init_tcpConnectionTable();
  if (should_init("tcpListenerTable")) init_tcpListenerTable();
  if (should_init("udpEndpointTable")) init_udpEndpointTable();
  if (should_init("hw_fsys")) init_hw_fsys();
  if (should_init("hw_mem")) init_hw_mem();
 
  //1, 3, 6, 1, 4, 1, 24389, 1, 33
  if (should_init("cpu")) init_cpu();
  if (should_init("cpu_linux")) init_cpu_linux();
  //1, 3, 6, 1, 2, 1, 25, 1
  if (should_init("hr_system")) init_hr_system();
  //1, 3, 6, 1, 2, 1, 25, 2 
  if (should_init("hr_storage")) init_hr_storage();
  //1, 3, 6, 1, 2, 1, 25, 3, 2
  if (should_init("hr_device")) init_hr_device();
  //1, 3, 6, 1, 2, 1, 25, 3, 3  
  if (should_init("hr_proc")) init_hr_proc();  
  //1, 3, 6, 1, 2, 1, 25, 3, 4
  if (should_init("hr_network")) init_hr_network();
  //1, 3, 6, 1, 2, 1, 25, 3, 5
  if (should_init("hr_print")) init_hr_print();
  //1, 3, 6, 1, 2, 1, 25, 3, 6
  if (should_init("hr_disk")) init_hr_disk();
  //1, 3, 6, 1, 2, 1, 25, 3, 7
  if (should_init("hr_partition")) init_hr_partition();
  //1, 3, 6, 1, 2, 1, 25, 3, 8
  if (should_init("hr_filesys")) init_hr_filesys();
  //1, 3, 6, 1, 2, 1, 25, 4
  //1, 3, 6, 1, 2, 1, 25, 5
  if (should_init("hr_swrun")) init_hr_swrun(); 
  
                                                   