/* soapTester.cpp
   Generated by gSOAP 2.8.0 from cusdk.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
/*
   Stand-alone server auto-test code:
   Takes request from standard input or over TCP/IP socket and returns
response to standard output or socket

   Compile:
   cc soapTester.c soapServer.c soapC.c stdsoap2.c

   Command line usage with redirect over stdin/out:
   > ./a.out < SomeTest.req.xml
   > ./a.out 12288 < SomeTest.req.xml
     Note: 12288 = SOAP_XML_INDENT | SOAP_XML_STRICT (see codes in stdsoap2.h)
   Command line usage to start server at port 8080:
   > a.out 12288 8080
*/

#include "soapcusdkService.h"

#ifndef SOAP_DEFMAIN
# define SOAP_DEFMAIN main	/* redefine to use your own main() */
#endif

int SOAP_DEFMAIN(int argc, char **argv)
{
	cusdkService service(argc > 1 ? atoi(argv[1]) : 0);
	if (argc <= 2)
		return service.serve();
	return service.run(atoi(argv[2]));
}


/** Auto-test server operation cusdk__DetectServer */
int cusdkService::DetectServer(cusdk__DetectServerReq detectReq, cusdk__DetectServerRsp &detectRsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__Login */
int cusdkService::Login(cusdk__LoginReq loginReq, cusdk__LoginRsp &loginRsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__Logout */
int cusdkService::Logout(cusdk__LogoutReq logoutReq, cusdk__LogoutRsp &logoutRsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SubscribeNotify */
int cusdkService::SubscribeNotify(cusdk__SubscribeNotifyReq req, cusdk__SubscribeNotifyRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UnsubscribeNotify */
int cusdkService::UnsubscribeNotify(cusdk__UnsubscribeNotifyReq req, cusdk__UnsubscribeNotifyRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetNotify */
int cusdkService::GetNotify(cusdk__GetNotifyReq req, cusdk__GetNotifyRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCUIList */
int cusdkService::GetCUIList(cusdk__GetCUIListReq req, cusdk__GetCUIListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDomainList */
int cusdkService::GetDomainList(cusdk__GetDomainListReq req, cusdk__GetDomainListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetupStream */
int cusdkService::SetupStream(cusdk__SetupStreamReq req, cusdk__SetupStreamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PlayStream */
int cusdkService::PlayStream(cusdk__PlayStreamReq req, cusdk__PlayStreamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopStream */
int cusdkService::StopStream(cusdk__StopStreamReq req, cusdk__StopStreamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SendKeyFrame */
int cusdkService::SendKeyFrame(cusdk__SendKeyFrameReq req, cusdk__SendKeyFrameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PtzCtrl */
int cusdkService::PtzCtrl(cusdk__PtzCtrlReq req, cusdk__PtzCtrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PtzLock */
int cusdkService::PtzLock(cusdk__PtzLockReq req, cusdk__PtzLockRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PtzUnlock */
int cusdkService::PtzUnlock(cusdk__PtzUnlockReq req, cusdk__PtzUnlockRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PtzUnlockAll */
int cusdkService::PtzUnlockAll(cusdk__PtzUnlockAllReq req, cusdk__PtzUnlockAllRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SendTransData */
int cusdkService::SendTransData(cusdk__SendTransDataReq req, cusdk__SendTransDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserInfo */
int cusdkService::GetUserInfo(cusdk__GetUserInfoReq req, cusdk__GetUserInfoRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserGroupInfo */
int cusdkService::GetUserGroupInfo(cusdk__GetUserGroupInfoReq req, cusdk__GetUserGroupInfoRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserData */
int cusdkService::GetUserData(cusdk__GetUserDataReq req, cusdk__GetUserDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetUserData */
int cusdkService::SetUserData(cusdk__SetUserDataReq req, cusdk__SetUserDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelUserData */
int cusdkService::DelUserData(cusdk__DelUserDataReq req, cusdk__DelUserDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartExportDeviceData */
int cusdkService::StartExportDeviceData(cusdk__StartExportDeviceDataReq req, cusdk__StartExportDeviceDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopExportDeviceData */
int cusdkService::StopExportDeviceData(cusdk__StopExportDeviceDataReq req, cusdk__StopExportDeviceDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevGroupByGroup */
int cusdkService::GetUserDevGroupByGroup(cusdk__GetUserDevGroupByGroupReq req, cusdk__GetUserDevGroupByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevByGroup */
int cusdkService::GetUserDevByGroup(cusdk__GetUserDevByGroupReq req, cusdk__GetUserDevByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevGroup */
int cusdkService::GetUserDevGroup(cusdk__GetUserDevGroupReq req, cusdk__GetUserDevGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDomainDevGroup */
int cusdkService::GetDomainDevGroup(cusdk__GetDomainDevGroupReq req, cusdk__GetDomainDevGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDev */
int cusdkService::GetUserDev(cusdk__GetUserDevReq req, cusdk__GetUserDevRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDevByDomain */
int cusdkService::GetUserDevByDomain(cusdk__GetDevByDomainReq req, cusdk__GetDevByDomainRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceGroupDeviceRelations */
int cusdkService::GetDeviceGroupDeviceRelations(cusdk__GetDeviceGroupDeviceRelationsReq req, cusdk__GetDeviceGroupDeviceRelationsRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateDeviceGroup */
int cusdkService::CreateDeviceGroup(cusdk__CreateDeviceGroupReq req, cusdk__CreateDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelDeviceGroup */
int cusdkService::DelDeviceGroup(cusdk__DelDeviceGroupReq req, cusdk__DelDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyDeviceGroup */
int cusdkService::ModifyDeviceGroup(cusdk__ModifyDeviceGroupReq req, cusdk__ModifyDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeviceGroupAddDevice */
int cusdkService::DeviceGroupAddDevice(cusdk__DeviceGroupAddDeviceReq req, cusdk__DeviceGroupAddDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeviceGroupAddGroup */
int cusdkService::DeviceGroupAddGroup(cusdk__DeviceGroupAddGroupReq req, cusdk__DeviceGroupAddGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeviceGroupDelDevice */
int cusdkService::DeviceGroupDelDevice(cusdk__DeviceGroupDelDeviceReq req, cusdk__DeviceGroupDelDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserList */
int cusdkService::GetUserList(cusdk__GetUserListReq req, cusdk__GetUserListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserGroupList */
int cusdkService::GetUserGroupList(cusdk__GetUserGroupListReq req, cusdk__GetUserGroupListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateUserGroup */
int cusdkService::CreateUserGroup(cusdk__CreateUserGroupReq req, cusdk__CreateUserGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelUserGroup */
int cusdkService::DelUserGroup(cusdk__DelUserGroupReq req, cusdk__DelUserGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyUserGroup */
int cusdkService::ModifyUserGroup(cusdk__ModifyUserGroupReq req, cusdk__ModifyUserGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateUser */
int cusdkService::CreateUser(cusdk__CreateUserReq req, cusdk__CreateUserRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelUser */
int cusdkService::DelUser(cusdk__DelUserReq req, cusdk__DelUserRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyUser */
int cusdkService::ModifyUser(cusdk__ModifyUserReq req, cusdk__ModifyUserRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ChangePassword */
int cusdkService::ChangePassword(cusdk__ChangePasswordReq req, cusdk__ChangePasswordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserGetDeviceByGroup */
int cusdkService::UserGetDeviceByGroup(cusdk__UserGetDeviceByGroupReq req, cusdk__UserGetDeviceByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserAddDevice */
int cusdkService::UserAddDevice(cusdk__UserAddDeviceReq req, cusdk__UserAddDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserDelDevice */
int cusdkService::UserDelDevice(cusdk__UserDelDeviceReq req, cusdk__UserDelDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserGetTVWall */
int cusdkService::UserGetTVWall(cusdk__UserGetTVWallReq req, cusdk__UserGetTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserAddTVWall */
int cusdkService::UserAddTVWall(cusdk__UserAddTVWallReq req, cusdk__UserAddTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserDelTVWall */
int cusdkService::UserDelTVWall(cusdk__UserDelTVWallReq req, cusdk__UserDelTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserModifyDevice */
int cusdkService::UserModifyDevice(cusdk__UserModifyDeviceReq req, cusdk__UserModifyDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetAuthorizationDevice */
int cusdkService::GetAuthorizationDevice(cusdk__GetAuthorizationDeviceReq req, cusdk__GetAuthorizationDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__AddAuthorizationDevice */
int cusdkService::AddAuthorizationDevice(cusdk__AddAuthorizationDeviceReq req, cusdk__AddAuthorizationDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelAuthorizationDevice */
int cusdkService::DelAuthorizationDevice(cusdk__DelAuthorizationDeviceReq req, cusdk__DelAuthorizationDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyAuthorizationDevice */
int cusdkService::ModifyAuthorizationDevice(cusdk__ModifyAuthorizationDeviceReq req, cusdk__ModifyAuthorizationDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceBaseInfo */
int cusdkService::GetDeviceBaseInfo(cusdk__GetDeviceBaseInfoReq req, cusdk__GetDeviceBaseInfoRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetRCSSysParam */
int cusdkService::GetRCSSysParam(cusdk__GetRCSSysParamReq req, cusdk__GetRCSSysParamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetRCSSysParam */
int cusdkService::SetRCSSysParam(cusdk__SetRCSSysParamReq req, cusdk__SetRCSSysParamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetNruList */
int cusdkService::GetNruList(cusdk__GetNruListReq req, cusdk__GetNruListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDiskList */
int cusdkService::GetDiskList(cusdk__GetDiskListReq req, cusdk__GetDiskListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetPuChnBinding */
int cusdkService::GetPuChnBinding(cusdk__GetPuChnBindingReq req, cusdk__GetPuChnBindingRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__BindPu */
int cusdkService::BindPu(cusdk__BindPuReq req, cusdk__BindPuRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UnbindPu */
int cusdkService::UnbindPu(cusdk__UnbindPuReq req, cusdk__UnbindPuRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryRecordDays */
int cusdkService::QueryRecordDays(cusdk__QueryRecordDaysReq req, cusdk__QueryRecordDaysRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryRecord */
int cusdkService::QueryRecord(cusdk__QueryRecordReq req, cusdk__QueryRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartPlatformRecord */
int cusdkService::StartPlatformRecord(cusdk__StartPlatformRecordReq req, cusdk__StartPlatformRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopPlatformRecord */
int cusdkService::StopPlatformRecord(cusdk__StopPlatformRecordReq req, cusdk__StopPlatformRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartPuRecord */
int cusdkService::StartPuRecord(cusdk__StartPuRecordReq req, cusdk__StartPuRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopPuRecord */
int cusdkService::StopPuRecord(cusdk__StopPuRecordReq req, cusdk__StopPuRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetupPlayRecord */
int cusdkService::SetupPlayRecord(cusdk__SetupPlayRecordReq req, cusdk__SetupPlayRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PlayRecord */
int cusdkService::PlayRecord(cusdk__PlayRecordReq req, cusdk__PlayRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__VcrCtrl */
int cusdkService::VcrCtrl(cusdk__VcrCtrlReq req, cusdk__VcrCtrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCurRecordPlayPosition */
int cusdkService::GetCurRecordPlayPosition(cusdk__GetCurRecordPlayPositionReq req, cusdk__GetCurRecordPlayPositionRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopPlayRecord */
int cusdkService::StopPlayRecord(cusdk__StopPlayRecordReq req, cusdk__StopPlayRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetupDownloadRecord */
int cusdkService::SetupDownloadRecord(cusdk__SetupDownloadRecordReq req, cusdk__SetupDownloadRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartDownloadRecord */
int cusdkService::StartDownloadRecord(cusdk__StartDownloadRecordReq req, cusdk__StartDownloadRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopDownloadRecord */
int cusdkService::StopDownloadRecord(cusdk__StopDownloadRecordReq req, cusdk__StopDownloadRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetRecordPlan */
int cusdkService::GetRecordPlan(cusdk__GetRecordPlanReq req, cusdk__GetRecordPlanRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetRecordPlan */
int cusdkService::SetRecordPlan(cusdk__SetRecordPlanReq req, cusdk__SetRecordPlanRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetAllTVWall */
int cusdkService::GetAllTVWall(cusdk__GetAllTVWallReq req, cusdk__GetAllTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetTVWall */
int cusdkService::GetTVWall(cusdk__GetTVWallReq req, cusdk__GetTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateTVWall */
int cusdkService::CreateTVWall(cusdk__CreateTVWallReq req, cusdk__CreateTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelTVWall */
int cusdkService::DelTVWall(cusdk__DelTVWallReq req, cusdk__DelTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyTVWall */
int cusdkService::ModifyTVWall(cusdk__ModifyTVWallReq req, cusdk__ModifyTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallStartPlay */
int cusdkService::TVWallStartPlay(cusdk__TVWallStartPlayReq req, cusdk__TVWallStartPlayRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallStopPlay */
int cusdkService::TVWallStopPlay(cusdk__TVWallStopPlayReq req, cusdk__TVWallStopPlayRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallWindowPollContrl */
int cusdkService::TVWallWindowPollContrl(cusdk__TVWallWindowPollContrlReq req, cusdk__TVWallWindowPollContrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallSaveScheme */
int cusdkService::TVWallSaveScheme(cusdk__TVWallSaveSchemeReq req, cusdk__TVWallSaveSchemeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallDelScheme */
int cusdkService::TVWallDelScheme(cusdk__TVWallDelSchemeReq req, cusdk__TVWallDelSchemeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallLoadScheme */
int cusdkService::TVWallLoadScheme(cusdk__TVWallLoadSchemeReq req, cusdk__TVWallLoadSchemeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallQueryScheme */
int cusdkService::TVWallQueryScheme(cusdk__TVWallQuerySchemeReq req, cusdk__TVWallQuerySchemeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallSetSchemePoll */
int cusdkService::TVWallSetSchemePoll(cusdk__TVWallSetSchemePollReq req, cusdk__TVWallSetSchemePollRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallGetSchemePoll */
int cusdkService::TVWallGetSchemePoll(cusdk__TVWallGetSchemePollReq req, cusdk__TVWallGetSchemePollRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallSchemePollControl */
int cusdkService::TVWallSchemePollControl(cusdk__TVWallSchemePollControlReq req, cusdk__TVWallSchemePollControlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetTVDivNum */
int cusdkService::SetTVDivNum(cusdk__SetTVDivNumReq req, cusdk__SetTVDivNumRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PlayRecordOnTVWall */
int cusdkService::PlayRecordOnTVWall(cusdk__PlayRecordOnTVWallReq req, cusdk__PlayRecordOnTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopPlayRecordOnTVWall */
int cusdkService::StopPlayRecordOnTVWall(cusdk__StopPlayRecordOnTVWallReq req, cusdk__StopPlayRecordOnTVWallRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetSupportMapTypes */
int cusdkService::GetSupportMapTypes(cusdk__GetSupportMapTypesReq req, cusdk__GetSupportMapTypesRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetMapImageUploadUrl */
int cusdkService::GetMapImageUploadUrl(cusdk__GetMapImageUploadUrlReq req, cusdk__GetMapImageUploadUrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateMap */
int cusdkService::CreateMap(cusdk__CreateMapReq req, cusdk__CreateMapRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyMap */
int cusdkService::ModifyMap(cusdk__ModifyMapReq req, cusdk__ModifyMapRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelMap */
int cusdkService::DelMap(cusdk__DelMapReq req, cusdk__DelMapRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryMap */
int cusdkService::QueryMap(cusdk__QueryMapReq req, cusdk__QueryMapRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryMapArea */
int cusdkService::QueryMapArea(cusdk__QueryMapAreaReq req, cusdk__QueryMapAreaRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateMapArea */
int cusdkService::CreateMapArea(cusdk__CreateMapAreaReq req, cusdk__CreateMapAreaRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyMapArea */
int cusdkService::ModifyMapArea(cusdk__ModifyMapAreaReq req, cusdk__ModifyMapAreaRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateMapElement */
int cusdkService::CreateMapElement(cusdk__CreateMapElementReq req, cusdk__CreateMapElementRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyMapElement */
int cusdkService::ModifyMapElement(cusdk__ModifyMapElementReq req, cusdk__ModifyMapElementRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelMapElement */
int cusdkService::DelMapElement(cusdk__DelMapElementReq req, cusdk__DelMapElementRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryMapElement */
int cusdkService::QueryMapElement(cusdk__QueryMapElementReq req, cusdk__QueryMapElementRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SearchMapElement */
int cusdkService::SearchMapElement(cusdk__SearchMapElementReq req, cusdk__SearchMapElementRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetMapElementImageUploadUrl */
int cusdkService::GetMapElementImageUploadUrl(cusdk__GetMapElementImageUploadUrlReq req, cusdk__GetMapElementImageUploadUrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryMapElementImageList */
int cusdkService::QueryMapElementImageList(cusdk__QueryMapElementImageListReq req, cusdk__QueryMapElementImageListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__MapPositionMar2Earth */
int cusdkService::MapPositionMar2Earth(cusdk__MapPositionMar2EarthReq req, cusdk__MapPositionMar2EarthRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__MapPositionEarth2Mar */
int cusdkService::MapPositionEarth2Mar(cusdk__MapPositionEarth2MarReq req, cusdk__MapPositionEarth2MarRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetEMapDataVersion */
int cusdkService::GetEMapDataVersion(cusdk__GetEMapDataVersionReq req, cusdk__GetEMapDataVersionRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetAlarmLinkDataVersion */
int cusdkService::GetAlarmLinkDataVersion(cusdk__GetAlarmLinkDataVersionReq req, cusdk__GetAlarmLinkDataVersionRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryAlarmLinkConfig */
int cusdkService::QueryAlarmLinkConfig(cusdk__QueryAlarmLinkConfigReq req, cusdk__QueryAlarmLinkConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetAlarmLinkConfig */
int cusdkService::GetAlarmLinkConfig(cusdk__GetAlarmLinkConfigReq req, cusdk__GetAlarmLinkConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetAlarmLinkConfig */
int cusdkService::SetAlarmLinkConfig(cusdk__SetAlarmLinkConfigReq req, cusdk__SetAlarmLinkConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryAlarmLinkArea */
int cusdkService::QueryAlarmLinkArea(cusdk__QueryAlarmLinkAreaReq req, cusdk__QueryAlarmLinkAreaRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateAlarmLinkArea */
int cusdkService::CreateAlarmLinkArea(cusdk__CreateAlarmLinkAreaReq req, cusdk__CreateAlarmLinkAreaRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelAlarmLinkArea */
int cusdkService::DelAlarmLinkArea(cusdk__DelAlarmLinkAreaReq req, cusdk__DelAlarmLinkAreaRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyAlarmLinkArea */
int cusdkService::ModifyAlarmLinkArea(cusdk__ModifyAlarmLinkAreaReq req, cusdk__ModifyAlarmLinkAreaRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryUserLog */
int cusdkService::QueryUserLog(cusdk__QueryUserLogReq req, cusdk__QueryUserLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartExportUserLog */
int cusdkService::StartExportUserLog(cusdk__StartExportUserLogReq req, cusdk__StartExportUserLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetExportUserLogProcess */
int cusdkService::GetExportUserLogProcess(cusdk__GetExportUserLogProcessReq req, cusdk__GetExportUserLogProcessRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopExportUserLog */
int cusdkService::StopExportUserLog(cusdk__StopExportUserLogReq req, cusdk__StopExportUserLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryDeviceLog */
int cusdkService::QueryDeviceLog(cusdk__QueryDeviceLogReq req, cusdk__QueryDeviceLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartExportDeviceLog */
int cusdkService::StartExportDeviceLog(cusdk__StartExportDeviceLogReq req, cusdk__StartExportDeviceLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetExportDeviceLogProcess */
int cusdkService::GetExportDeviceLogProcess(cusdk__GetExportDeviceLogProcessReq req, cusdk__GetExportDeviceLogProcessRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopExportDeviceLog */
int cusdkService::StopExportDeviceLog(cusdk__StopExportDeviceLogReq req, cusdk__StopExportDeviceLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryAlarmLog */
int cusdkService::QueryAlarmLog(cusdk__QueryAlarmLogReq req, cusdk__QueryAlarmLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartExportAlarmLog */
int cusdkService::StartExportAlarmLog(cusdk__StartExportAlarmLogReq req, cusdk__StartExportAlarmLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetExportAlarmLogProcess */
int cusdkService::GetExportAlarmLogProcess(cusdk__GetExportAlarmLogProcessReq req, cusdk__GetExportAlarmLogProcessRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StopExportAlarmLog */
int cusdkService::StopExportAlarmLog(cusdk__StopExportAlarmLogReq req, cusdk__StopExportAlarmLogRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetLogConfig */
int cusdkService::GetLogConfig(cusdk__GetLogConfigReq req, cusdk__GetLogConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetLogConfig */
int cusdkService::SetLogConfig(cusdk__SetLogConfigReq req, cusdk__SetLogConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CallPu */
int cusdkService::CallPu(cusdk__CallPuReq req, cusdk__CallPuRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__HangUpPu */
int cusdkService::HangUpPu(cusdk__HangUpPuReq req, cusdk__HangUpPuRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceEncoderParam */
int cusdkService::GetDeviceEncoderParam(cusdk__GetDeviceEncoderParamReq req, cusdk__GetDeviceEncoderParamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceAudioEncoderParam */
int cusdkService::GetDeviceAudioEncoderParam(cusdk__GetDeviceAudioEncoderParamReq req, cusdk__GetDeviceAudioEncoderParamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetDeviceEncoderParam */
int cusdkService::SetDeviceEncoderParam(cusdk__SetDeviceEncoderParamReq req, cusdk__SetDeviceEncoderParamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetPuVidSrcOSD */
int cusdkService::SetPuVidSrcOSD(cusdk__SetPuVidSrcOSDReq req, cusdk__SetPuVidSrcOSDRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetPuVidSrcOSD */
int cusdkService::GetPuVidSrcOSD(cusdk__GetPuVidSrcOSDReq req, cusdk__GetPuVidSrcOSDRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetDeviceName */
int cusdkService::SetDeviceName(cusdk__SetDeviceNameReq req, cusdk__SetDeviceNameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCameraProtocolType */
int cusdkService::GetCameraProtocolType(cusdk__GetCameraProtocolTypeReq req, cusdk__GetCameraProtocolTypeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetCameraProtocolType */
int cusdkService::SetCameraProtocolType(cusdk__SetCameraProtocolTypeReq req, cusdk__SetCameraProtocolTypeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetMotionDetectConfig */
int cusdkService::GetMotionDetectConfig(cusdk__GetMotionDetectConfigReq req, cusdk__GetMotionDetectConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetMotionDetectConfig */
int cusdkService::SetMotionDetectConfig(cusdk__SetMotionDetectConfigReq req, cusdk__SetMotionDetectConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetShadeConfig */
int cusdkService::GetShadeConfig(cusdk__GetShadeConfigReq req, cusdk__GetShadeConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetShadeConfig */
int cusdkService::SetShadeConfig(cusdk__SetShadeConfigReq req, cusdk__SetShadeConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceChannelName */
int cusdkService::GetDeviceChannelName(cusdk__GetDeviceChannelNameReq req, cusdk__GetDeviceChannelNameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetDeviceChannelName */
int cusdkService::SetDeviceChannelName(cusdk__SetDeviceChannelNameReq req, cusdk__SetDeviceChannelNameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetSyncVideoSrcNameEnable */
int cusdkService::GetSyncVideoSrcNameEnable(cusdk__GetSyncVideoSrcNameEnableReq req, cusdk__GetSyncVideoSrcNameEnableRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetSyncVideoSrcNameEnable */
int cusdkService::SetSyncVideoSrcNameEnable(cusdk__SetSyncVideoSrcNameEnableReq req, cusdk__SetSyncVideoSrcNameEnableRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetPtzPresetName */
int cusdkService::GetPtzPresetName(cusdk__GetPtzPresetNameReq req, cusdk__GetPtzPresetNameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetPtzPresetName */
int cusdkService::SetPtzPresetName(cusdk__SetPtzPresetNameReq req, cusdk__SetPtzPresetNameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DelPtzPresetName */
int cusdkService::DelPtzPresetName(cusdk__DelPtzPresetNameReq req, cusdk__DelPtzPresetNameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__VsipChannelData */
int cusdkService::VsipChannelData(cusdk__VsipChannelDataReq req, cusdk__VsipChannelDataRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetTransDataParam */
int cusdkService::SetTransDataParam(cusdk__SetTransDataParamReq req, cusdk__SetTransDataParamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetTransDataParam */
int cusdkService::GetTransDataParam(cusdk__GetTransDataParamReq req, cusdk__GetTransDataParamRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryGPSTrace */
int cusdkService::QueryGPSTrace(cusdk__QueryGPSTraceReq req, cusdk__QueryGPSTraceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetMapConfig */
int cusdkService::GetMapConfig(cusdk__GetMapConfigReq req, cusdk__GetMapConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetMapConfig */
int cusdkService::SetMapConfig(cusdk__SetMapConfigReq req, cusdk__SetMapConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceSerialConfig */
int cusdkService::GetDeviceSerialConfig(cusdk__GetDeviceSerialConfigReq req, cusdk__GetDeviceSerialConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetDeviceSerialConfig */
int cusdkService::SetDeviceSerialConfig(cusdk__SetDeviceSerialConfigReq req, cusdk__SetDeviceSerialConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceGBID */
int cusdkService::GetDeviceGBID(cusdk__GetDeviceGBIDReq req, cusdk__GetDeviceGBIDRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCivilcode */
int cusdkService::GetCivilcode(cusdk__GetCivilcodeReq req, cusdk__GetCivilcodeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceChnByGBID */
int cusdkService::GetDeviceChnByGBID(cusdk__GetDeviceChnByGBIDReq req, cusdk__GetDeviceChnByGBIDRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCAPSConfig */
int cusdkService::GetCAPSConfig(cusdk__GetCAPSConfigReq req, cusdk__GetCAPSConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetCAPSConfig */
int cusdkService::SetCAPSConfig(cusdk__SetCAPSConfigReq req, cusdk__SetCAPSConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryCAPSDeviceList */
int cusdkService::QueryCAPSDeviceList(cusdk__QueryCAPSDeviceListReq req, cusdk__QueryCAPSDeviceListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CAPSAddDevice */
int cusdkService::CAPSAddDevice(cusdk__CAPSAddDeviceReq req, cusdk__CAPSAddDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CAPSModifyDevice */
int cusdkService::CAPSModifyDevice(cusdk__CAPSModifyDeviceReq req, cusdk__CAPSModifyDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CAPSDelDevice */
int cusdkService::CAPSDelDevice(cusdk__CAPSDelDeviceReq req, cusdk__CAPSDelDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetOfflineDeviceStat */
int cusdkService::GetOfflineDeviceStat(cusdk__GetOfflineDeviceStatReq req, cusdk__GetOfflineDeviceStatRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UpdateCUProperty */
int cusdkService::UpdateCUProperty(cusdk__UpdateCUPropertyReq req, cusdk__UpdateCUPropertyRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__RestartDevice */
int cusdkService::RestartDevice(cusdk__RestartDeviceReq req, cusdk__RestartDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserAddDeviceGroup */
int cusdkService::UserAddDeviceGroup(cusdk__UserAddDeviceGroupReq req, cusdk__UserAddDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserDelDeviceGroup */
int cusdkService::UserDelDeviceGroup(cusdk__UserDelDeviceGroupReq req, cusdk__UserDelDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserGroupAddDeviceGroup */
int cusdkService::UserGroupAddDeviceGroup(cusdk__UserGroupAddDeviceGroupReq req, cusdk__UserGroupAddDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserGroupDelDeviceGroup */
int cusdkService::UserGroupDelDeviceGroup(cusdk__UserGroupDelDeviceGroupReq req, cusdk__UserGroupDelDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserSetAutoSyncDeviceGroup */
int cusdkService::UserSetAutoSyncDeviceGroup(cusdk__UserSetAutoSyncDeviceGroupReq req, cusdk__UserSetAutoSyncDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserGroupSetAutoSyncDeviceGroup */
int cusdkService::UserGroupSetAutoSyncDeviceGroup(cusdk__UserGroupSetAutoSyncDeviceGroupReq req, cusdk__UserGroupSetAutoSyncDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryOperationProgress */
int cusdkService::QueryOperationProgress(cusdk__QueryOperationProgreeReq req, cusdk__QueryOperationProgreeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserQueryAutoSyncDeviceGroup */
int cusdkService::UserQueryAutoSyncDeviceGroup(cusdk__UserQueryAutoSyncDeviceGroupReq req, cusdk__UserQueryAutoSyncDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UserGroupQueryAutoSyncDeviceGroup */
int cusdkService::UserGroupQueryAutoSyncDeviceGroup(cusdk__UserGroupQueryAutoSyncDeviceGroupReq req, cusdk__UserGroupQueryAutoSyncDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetSuperGBDomainList */
int cusdkService::GetSuperGBDomainList(cusdk__GetGBDomainListReq req, cusdk__GetGBDomainListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__PushDevice */
int cusdkService::PushDevice(cusdk__DevicePushReq req, cusdk__DevicePushRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDataVersion */
int cusdkService::GetDataVersion(cusdk__GetDataVersionReq req, cusdk__GetDataVersionRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartDataFileExport */
int cusdkService::StartDataFileExport(cusdk__StartDataFileExportReq req, cusdk__StartDataFileExportRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__EndDataFileExport */
int cusdkService::EndDataFileExport(cusdk__EndDataFileExportReq req, cusdk__EndDataFileExportRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartDataFileImport */
int cusdkService::StartDataFileImport(cusdk__StartDataFileImportReq req, cusdk__StartDataFileImportRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__EndDataFileImport */
int cusdkService::EndDataFileImport(cusdk__EndDataFileImportReq req, cusdk__EndDataFileImportRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetOperationProgress */
int cusdkService::GetOperationProgress(cusdk__GetOperationProgreeReq req, cusdk__GetOperationProgreeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetChildrenGBDomainList */
int cusdkService::GetChildrenGBDomainList(cusdk__GetChildrenGBDomainListReq req, cusdk__GetChildrenGBDomainListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetGBDevciePushDomain */
int cusdkService::GetGBDevciePushDomain(cusdk__GetGBDevicePushDomainReq req, cusdk__GetGBDevicePushDomainRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UpdateOperationProgress */
int cusdkService::UpdateOperationProgress(cusdk__UpdateOperationProgreeReq req, cusdk__UpdateOperationProgreeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetResInfo */
int cusdkService::GetResInfo(cusdk__ResInfoReq cResInfoReq, cusdk__ResInfoRsp &cResInfoRsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SearchDevice */
int cusdkService::SearchDevice(cusdk__SearchDeviceReq req, cusdk__SearchDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetSearchResult */
int cusdkService::GetSearchResult(cusdk__GetSearchResultReq req, cusdk__GetSearchResultRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetSearchResultByGroup */
int cusdkService::GetSearchResultByGroup(cusdk__GetSearchResultByGroupReq req, cusdk__GetSearchResultByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__EndOperation */
int cusdkService::EndOperation(cusdk__EndOperationReq req, cusdk__EndOperationRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceGroup */
int cusdkService::GetDeviceGroup(cusdk__GetDeviceGroupReq req, cusdk__GetDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDevice */
int cusdkService::GetDevice(cusdk__GetDeviceReq req, cusdk__GetDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceGroupPath */
int cusdkService::GetDeviceGroupPath(cusdk__GetDeviceGroupPathReq req, cusdk__GetDeviceGroupPathRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__CreateCustomTreeView */
int cusdkService::CreateCustomTreeView(cusdk__CreateCustomTreeViewReq req, cusdk__CreateCustomTreeViewRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyCustomTreeViewName */
int cusdkService::ModifyCustomTreeViewName(cusdk__ModifyCustomTreeViewNameReq req, cusdk__ModifyCustomTreeViewNameRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeleteCustomTreeView */
int cusdkService::DeleteCustomTreeView(cusdk__DeleteCustomTreeViewReq req, cusdk__DeleteCustomTreeViewRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCustomTreeViewList */
int cusdkService::GetCustomTreeViewList(cusdk__GetCustomTreeViewListReq req, cusdk__GetCustomTreeViewListRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetUserDeviceInGroup */
int cusdkService::GetUserDeviceInGroup(cusdk__GetUserDeviceInGroupReq req, cusdk__GetUserDeviceInGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__BatchOperation */
int cusdkService::BatchOperation(cusdk__BatchOperationReq req, cusdk__BatchOperationRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceGroupVideoSrcNum */
int cusdkService::GetDeviceGroupVideoSrcNum(cusdk__GetDeviceGroupVideoSrcNumReq req, cusdk__GetDeviceGroupVideoSrcNumRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetVSOfflineInfo */
int cusdkService::GetVSOfflineInfo(cusdk__GetVSOfflineInfoReq req, cusdk__GetVSOfflineInfoRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDevAzimuthalAngle */
int cusdkService::GetDevAzimuthalAngle(cusdk__GetDevAzimuthalAngleReq req, cusdk__GetDevAzimuthalAngleRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeleteRecord */
int cusdkService::DeleteRecord(cusdk__DeleteRecordReq req, cusdk__DeleteRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__AutoMatchGBId */
int cusdkService::AutoMatchGBId(cusdk__AutoMatchGBIdReq req, cusdk__AutoMatchGBIdRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetGroupDevSumNum */
int cusdkService::GetGroupDevSumNum(cusdk__GetGroupDevSumNumReq req, cusdk__GetGroupDevSumNumRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyGBDeviceGroup */
int cusdkService::ModifyGBDeviceGroup(cusdk__ModifyGBDeviceGroupReq req, cusdk__ModifyGBDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ModifyGBDevice */
int cusdkService::ModifyGBDevice(cusdk__ModifyGBDeviceReq req, cusdk__ModifyGBDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StartDevicePush */
int cusdkService::StartDevicePush(cusdk__StartDevicePushReq req, cusdk__StartDevicePushRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetGBDeviceByGroup */
int cusdkService::GetGBDeviceByGroup(cusdk__GetGBDeviceByGroupReq req, cusdk__GetGBDeviceByGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SearchGBDevice */
int cusdkService::SearchGBDevice(cusdk__SearchGBDeviceReq req, cusdk__SearchGBDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SearchGBDeviceGroup */
int cusdkService::SearchGBDeviceGroup(cusdk__SearchGBDeviceGroupReq req, cusdk__SearchGBDeviceGroupRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetNextDeviceGBIDError */
int cusdkService::GetNextDeviceGBIDError(cusdk__GetNextDeviceGBIDErrorReq req, cusdk__GetNextDeviceGBIDErrorRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetServerConfig */
int cusdkService::GetServerConfig(cusdk__GetServerConfigReq req, cusdk__GetServerConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetServerConfig */
int cusdkService::SetServerConfig(cusdk__SetServerConfigReq req, cusdk__SetServerConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__TVWallClearAlarm */
int cusdkService::TVWallClearAlarm(cusdk__TVWallClearAlarmReq req, cusdk__TVWallClearAlarmRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__LockRecord */
int cusdkService::LockRecord(cusdk__LockRecordReq req, cusdk__LockRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UnlockRecord */
int cusdkService::UnlockRecord(cusdk__UnlockRecordReq req, cusdk__UnlockRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetPULongOSD */
int cusdkService::GetPULongOSD(cusdk__GetPULongOSDReq req, cusdk__GetPULongOSDRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetPULongOSD */
int cusdkService::SetPULongOSD(cusdk__SetPULongOSDReq req, cusdk__SetPULongOSDRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceCertificate */
int cusdkService::GetDeviceCertificate(cusdk__GetDeviceCertificateReq req, cusdk__GetDeviceCertificateRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeviceSignatrueCtrl */
int cusdkService::DeviceSignatrueCtrl(cusdk__DeviceSignatrueCtrlReq req, cusdk__DeviceSignatrueCtrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__DeviceEncryptionCtrl */
int cusdkService::DeviceEncryptionCtrl(cusdk__DeviceEncryptionCtrlReq req, cusdk__DeviceEncryptionCtrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__BidirectionalAuth1 */
int cusdkService::BidirectionalAuth1(cusdk__BidirectionalAuth1Req req, cusdk__BidirectionalAuth1Rsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__BidirectionalAuth2 */
int cusdkService::BidirectionalAuth2(cusdk__BidirectionalAuth2Req req, cusdk__BidirectionalAuth2Rsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__AdjustVideoSrcOrder */
int cusdkService::AdjustVideoSrcOrder(cusdk__AdjustVideoSrcOrderReq req, cusdk__AdjustVideoSrcOrderRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetAlarmTypes */
int cusdkService::GetAlarmTypes(cusdk__GetAlarmTypesReq req, cusdk__GetAlarmTypesRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__EliminateAlarm */
int cusdkService::EliminateAlarm(cusdk__EliminateAlarmReq req, cusdk__EliminateAlarmRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetDeviceRecordsServerUrl */
int cusdkService::GetDeviceRecordsServerUrl(cusdk__GetDeviceRecordsServerUrlReq req, cusdk__GetDeviceRecordsServerUrlRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__LockRecordBatch */
int cusdkService::LockRecordBatch(cusdk__LockRecordBatchReq req, cusdk__LockRecordBatchRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__UnlockRecordBatch */
int cusdkService::UnlockRecordBatch(cusdk__UnlockRecordBatchReq req, cusdk__UnlockRecordBatchRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryLockedRecord */
int cusdkService::QueryLockedRecord(cusdk__QueryLockedRecordReq req, cusdk__QueryLockedRecordRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetStreamPreDispatchConfig */
int cusdkService::GetStreamPreDispatchConfig(cusdk__GetStreamPreDispatchConfigReq req, cusdk__GetStreamPreDispatchConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetStreamPreDispatchConfig */
int cusdkService::SetStreamPreDispatchConfig(cusdk__SetStreamPreDispatchConfigReq req, cusdk__SetStreamPreDispatchConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__QueryStreamPreDispatchDevice */
int cusdkService::QueryStreamPreDispatchDevice(cusdk__QueryStreamPreDispatchDeviceReq req, cusdk__QueryStreamPreDispatchDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StreamPreDispatchAddDevice */
int cusdkService::StreamPreDispatchAddDevice(cusdk__StreamPreDispatchAddDeviceReq req, cusdk__StreamPreDispatchAddDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__StreamPreDispatchDelDevice */
int cusdkService::StreamPreDispatchDelDevice(cusdk__StreamPreDispatchDelDeviceReq req, cusdk__StreamPreDispatchDelDeviceRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetEncChnRes */
int cusdkService::GetEncChnRes(cusdk__GetEncChnResReq req, cusdk__GetEncChnResRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__AllocEncChnRes */
int cusdkService::AllocEncChnRes(cusdk__AllocEncChnResReq req, cusdk__AllocEncChnResRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__ReleaseEncChnRes */
int cusdkService::ReleaseEncChnRes(cusdk__ReleaseEncChnResReq req, cusdk__ReleaseEncChnResRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GBPuTransdataSsSet */
int cusdkService::GBPuTransdataSsSet(cusdk__GBPuTransdataSsSetReq req, cusdk__GBPuTransdataSsSetRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetGBDomainPrivilege */
int cusdkService::GetGBDomainPrivilege(cusdk__GetGBDomainPrivilegeReq req, cusdk__GetGBDomainPrivilegeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetGBDomainPrivilege */
int cusdkService::SetGBDomainPrivilege(cusdk__SetGBDomainPrivilegeReq req, cusdk__SetGBDomainPrivilegeRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetGBConfig */
int cusdkService::GetGBConfig(cusdk__GetGBConfigReq req, cusdk__GetGBConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetGBConfig */
int cusdkService::SetGBConfig(cusdk__SetGBConfigReq req, cusdk__SetGBConfigRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__SetCertificate */
int cusdkService::SetCertificate(cusdk__SetCertificateReq req, cusdk__SetCertificateRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}


/** Auto-test server operation cusdk__GetCertificate */
int cusdkService::GetCertificate(cusdk__GetCertificateReq req, cusdk__GetCertificateRsp &rsp)
{	
	/* Return incomplete response with default data values */
	return SOAP_OK;
}
