/* soapcusdkService.h
   Generated by gSOAP 2.8.0 from cusdk.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapcusdkService_H
#define soapcusdkService_H
#include "soapH.h"
class SOAP_CMAC cusdkService : public soap
{ public:
	/// Constructor
	cusdkService();
	/// Constructor with copy of another engine state
	cusdkService(const struct soap&);
	/// Constructor with engine input+output mode control
	cusdkService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	cusdkService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~cusdkService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Initializer used by constructor
	virtual	void cusdkService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	cusdkService *copy();
	/// Force close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	///

	/// Web service operation 'DetectServer' (returns error code or SOAP_OK)
	virtual	int DetectServer(cusdk__DetectServerReq detectReq, cusdk__DetectServerRsp &detectRsp);

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login(cusdk__LoginReq loginReq, cusdk__LoginRsp &loginRsp);

	/// Web service operation 'Logout' (returns error code or SOAP_OK)
	virtual	int Logout(cusdk__LogoutReq logoutReq, cusdk__LogoutRsp &logoutRsp);

	/// Web service operation 'SubscribeNotify' (returns error code or SOAP_OK)
	virtual	int SubscribeNotify(cusdk__SubscribeNotifyReq req, cusdk__SubscribeNotifyRsp &rsp);

	/// Web service operation 'UnsubscribeNotify' (returns error code or SOAP_OK)
	virtual	int UnsubscribeNotify(cusdk__UnsubscribeNotifyReq req, cusdk__UnsubscribeNotifyRsp &rsp);

	/// Web service operation 'GetNotify' (returns error code or SOAP_OK)
	virtual	int GetNotify(cusdk__GetNotifyReq req, cusdk__GetNotifyRsp &rsp);

	/// Web service operation 'GetCUIList' (returns error code or SOAP_OK)
	virtual	int GetCUIList(cusdk__GetCUIListReq req, cusdk__GetCUIListRsp &rsp);

	/// Web service operation 'GetDomainList' (returns error code or SOAP_OK)
	virtual	int GetDomainList(cusdk__GetDomainListReq req, cusdk__GetDomainListRsp &rsp);

	/// Web service operation 'SetupStream' (returns error code or SOAP_OK)
	virtual	int SetupStream(cusdk__SetupStreamReq req, cusdk__SetupStreamRsp &rsp);

	/// Web service operation 'PlayStream' (returns error code or SOAP_OK)
	virtual	int PlayStream(cusdk__PlayStreamReq req, cusdk__PlayStreamRsp &rsp);

	/// Web service operation 'StopStream' (returns error code or SOAP_OK)
	virtual	int StopStream(cusdk__StopStreamReq req, cusdk__StopStreamRsp &rsp);

	/// Web service operation 'SendKeyFrame' (returns error code or SOAP_OK)
	virtual	int SendKeyFrame(cusdk__SendKeyFrameReq req, cusdk__SendKeyFrameRsp &rsp);

	/// Web service operation 'PtzCtrl' (returns error code or SOAP_OK)
	virtual	int PtzCtrl(cusdk__PtzCtrlReq req, cusdk__PtzCtrlRsp &rsp);

	/// Web service operation 'PtzLock' (returns error code or SOAP_OK)
	virtual	int PtzLock(cusdk__PtzLockReq req, cusdk__PtzLockRsp &rsp);

	/// Web service operation 'PtzUnlock' (returns error code or SOAP_OK)
	virtual	int PtzUnlock(cusdk__PtzUnlockReq req, cusdk__PtzUnlockRsp &rsp);

	/// Web service operation 'PtzUnlockAll' (returns error code or SOAP_OK)
	virtual	int PtzUnlockAll(cusdk__PtzUnlockAllReq req, cusdk__PtzUnlockAllRsp &rsp);

	/// Web service operation 'SendTransData' (returns error code or SOAP_OK)
	virtual	int SendTransData(cusdk__SendTransDataReq req, cusdk__SendTransDataRsp &rsp);

	/// Web service operation 'GetUserInfo' (returns error code or SOAP_OK)
	virtual	int GetUserInfo(cusdk__GetUserInfoReq req, cusdk__GetUserInfoRsp &rsp);

	/// Web service operation 'GetUserGroupInfo' (returns error code or SOAP_OK)
	virtual	int GetUserGroupInfo(cusdk__GetUserGroupInfoReq req, cusdk__GetUserGroupInfoRsp &rsp);

	/// Web service operation 'GetUserData' (returns error code or SOAP_OK)
	virtual	int GetUserData(cusdk__GetUserDataReq req, cusdk__GetUserDataRsp &rsp);

	/// Web service operation 'SetUserData' (returns error code or SOAP_OK)
	virtual	int SetUserData(cusdk__SetUserDataReq req, cusdk__SetUserDataRsp &rsp);

	/// Web service operation 'DelUserData' (returns error code or SOAP_OK)
	virtual	int DelUserData(cusdk__DelUserDataReq req, cusdk__DelUserDataRsp &rsp);

	/// Web service operation 'StartExportDeviceData' (returns error code or SOAP_OK)
	virtual	int StartExportDeviceData(cusdk__StartExportDeviceDataReq req, cusdk__StartExportDeviceDataRsp &rsp);

	/// Web service operation 'StopExportDeviceData' (returns error code or SOAP_OK)
	virtual	int StopExportDeviceData(cusdk__StopExportDeviceDataReq req, cusdk__StopExportDeviceDataRsp &rsp);

	/// Web service operation 'GetUserDevGroupByGroup' (returns error code or SOAP_OK)
	virtual	int GetUserDevGroupByGroup(cusdk__GetUserDevGroupByGroupReq req, cusdk__GetUserDevGroupByGroupRsp &rsp);

	/// Web service operation 'GetUserDevByGroup' (returns error code or SOAP_OK)
	virtual	int GetUserDevByGroup(cusdk__GetUserDevByGroupReq req, cusdk__GetUserDevByGroupRsp &rsp);

	/// Web service operation 'GetUserDevGroup' (returns error code or SOAP_OK)
	virtual	int GetUserDevGroup(cusdk__GetUserDevGroupReq req, cusdk__GetUserDevGroupRsp &rsp);

	/// Web service operation 'GetDomainDevGroup' (returns error code or SOAP_OK)
	virtual	int GetDomainDevGroup(cusdk__GetDomainDevGroupReq req, cusdk__GetDomainDevGroupRsp &rsp);

	/// Web service operation 'GetUserDev' (returns error code or SOAP_OK)
	virtual	int GetUserDev(cusdk__GetUserDevReq req, cusdk__GetUserDevRsp &rsp);

	/// Web service operation 'GetUserDevByDomain' (returns error code or SOAP_OK)
	virtual	int GetUserDevByDomain(cusdk__GetDevByDomainReq req, cusdk__GetDevByDomainRsp &rsp);

	/// Web service operation 'GetDeviceGroupDeviceRelations' (returns error code or SOAP_OK)
	virtual	int GetDeviceGroupDeviceRelations(cusdk__GetDeviceGroupDeviceRelationsReq req, cusdk__GetDeviceGroupDeviceRelationsRsp &rsp);

	/// Web service operation 'CreateDeviceGroup' (returns error code or SOAP_OK)
	virtual	int CreateDeviceGroup(cusdk__CreateDeviceGroupReq req, cusdk__CreateDeviceGroupRsp &rsp);

	/// Web service operation 'DelDeviceGroup' (returns error code or SOAP_OK)
	virtual	int DelDeviceGroup(cusdk__DelDeviceGroupReq req, cusdk__DelDeviceGroupRsp &rsp);

	/// Web service operation 'ModifyDeviceGroup' (returns error code or SOAP_OK)
	virtual	int ModifyDeviceGroup(cusdk__ModifyDeviceGroupReq req, cusdk__ModifyDeviceGroupRsp &rsp);

	/// Web service operation 'DeviceGroupAddDevice' (returns error code or SOAP_OK)
	virtual	int DeviceGroupAddDevice(cusdk__DeviceGroupAddDeviceReq req, cusdk__DeviceGroupAddDeviceRsp &rsp);

	/// Web service operation 'DeviceGroupAddGroup' (returns error code or SOAP_OK)
	virtual	int DeviceGroupAddGroup(cusdk__DeviceGroupAddGroupReq req, cusdk__DeviceGroupAddGroupRsp &rsp);

	/// Web service operation 'DeviceGroupDelDevice' (returns error code or SOAP_OK)
	virtual	int DeviceGroupDelDevice(cusdk__DeviceGroupDelDeviceReq req, cusdk__DeviceGroupDelDeviceRsp &rsp);

	/// Web service operation 'GetUserList' (returns error code or SOAP_OK)
	virtual	int GetUserList(cusdk__GetUserListReq req, cusdk__GetUserListRsp &rsp);

	/// Web service operation 'GetUserGroupList' (returns error code or SOAP_OK)
	virtual	int GetUserGroupList(cusdk__GetUserGroupListReq req, cusdk__GetUserGroupListRsp &rsp);

	/// Web service operation 'CreateUserGroup' (returns error code or SOAP_OK)
	virtual	int CreateUserGroup(cusdk__CreateUserGroupReq req, cusdk__CreateUserGroupRsp &rsp);

	/// Web service operation 'DelUserGroup' (returns error code or SOAP_OK)
	virtual	int DelUserGroup(cusdk__DelUserGroupReq req, cusdk__DelUserGroupRsp &rsp);

	/// Web service operation 'ModifyUserGroup' (returns error code or SOAP_OK)
	virtual	int ModifyUserGroup(cusdk__ModifyUserGroupReq req, cusdk__ModifyUserGroupRsp &rsp);

	/// Web service operation 'CreateUser' (returns error code or SOAP_OK)
	virtual	int CreateUser(cusdk__CreateUserReq req, cusdk__CreateUserRsp &rsp);

	/// Web service operation 'DelUser' (returns error code or SOAP_OK)
	virtual	int DelUser(cusdk__DelUserReq req, cusdk__DelUserRsp &rsp);

	/// Web service operation 'ModifyUser' (returns error code or SOAP_OK)
	virtual	int ModifyUser(cusdk__ModifyUserReq req, cusdk__ModifyUserRsp &rsp);

	/// Web service operation 'ChangePassword' (returns error code or SOAP_OK)
	virtual	int ChangePassword(cusdk__ChangePasswordReq req, cusdk__ChangePasswordRsp &rsp);

	/// Web service operation 'UserGetDeviceByGroup' (returns error code or SOAP_OK)
	virtual	int UserGetDeviceByGroup(cusdk__UserGetDeviceByGroupReq req, cusdk__UserGetDeviceByGroupRsp &rsp);

	/// Web service operation 'UserAddDevice' (returns error code or SOAP_OK)
	virtual	int UserAddDevice(cusdk__UserAddDeviceReq req, cusdk__UserAddDeviceRsp &rsp);

	/// Web service operation 'UserDelDevice' (returns error code or SOAP_OK)
	virtual	int UserDelDevice(cusdk__UserDelDeviceReq req, cusdk__UserDelDeviceRsp &rsp);

	/// Web service operation 'UserGetTVWall' (returns error code or SOAP_OK)
	virtual	int UserGetTVWall(cusdk__UserGetTVWallReq req, cusdk__UserGetTVWallRsp &rsp);

	/// Web service operation 'UserAddTVWall' (returns error code or SOAP_OK)
	virtual	int UserAddTVWall(cusdk__UserAddTVWallReq req, cusdk__UserAddTVWallRsp &rsp);

	/// Web service operation 'UserDelTVWall' (returns error code or SOAP_OK)
	virtual	int UserDelTVWall(cusdk__UserDelTVWallReq req, cusdk__UserDelTVWallRsp &rsp);

	/// Web service operation 'UserModifyDevice' (returns error code or SOAP_OK)
	virtual	int UserModifyDevice(cusdk__UserModifyDeviceReq req, cusdk__UserModifyDeviceRsp &rsp);

	/// Web service operation 'GetAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int GetAuthorizationDevice(cusdk__GetAuthorizationDeviceReq req, cusdk__GetAuthorizationDeviceRsp &rsp);

	/// Web service operation 'AddAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int AddAuthorizationDevice(cusdk__AddAuthorizationDeviceReq req, cusdk__AddAuthorizationDeviceRsp &rsp);

	/// Web service operation 'DelAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int DelAuthorizationDevice(cusdk__DelAuthorizationDeviceReq req, cusdk__DelAuthorizationDeviceRsp &rsp);

	/// Web service operation 'ModifyAuthorizationDevice' (returns error code or SOAP_OK)
	virtual	int ModifyAuthorizationDevice(cusdk__ModifyAuthorizationDeviceReq req, cusdk__ModifyAuthorizationDeviceRsp &rsp);

	/// Web service operation 'GetDeviceBaseInfo' (returns error code or SOAP_OK)
	virtual	int GetDeviceBaseInfo(cusdk__GetDeviceBaseInfoReq req, cusdk__GetDeviceBaseInfoRsp &rsp);

	/// Web service operation 'GetRCSSysParam' (returns error code or SOAP_OK)
	virtual	int GetRCSSysParam(cusdk__GetRCSSysParamReq req, cusdk__GetRCSSysParamRsp &rsp);

	/// Web service operation 'SetRCSSysParam' (returns error code or SOAP_OK)
	virtual	int SetRCSSysParam(cusdk__SetRCSSysParamReq req, cusdk__SetRCSSysParamRsp &rsp);

	/// Web service operation 'GetNruList' (returns error code or SOAP_OK)
	virtual	int GetNruList(cusdk__GetNruListReq req, cusdk__GetNruListRsp &rsp);

	/// Web service operation 'GetDiskList' (returns error code or SOAP_OK)
	virtual	int GetDiskList(cusdk__GetDiskListReq req, cusdk__GetDiskListRsp &rsp);

	/// Web service operation 'GetPuChnBinding' (returns error code or SOAP_OK)
	virtual	int GetPuChnBinding(cusdk__GetPuChnBindingReq req, cusdk__GetPuChnBindingRsp &rsp);

	/// Web service operation 'BindPu' (returns error code or SOAP_OK)
	virtual	int BindPu(cusdk__BindPuReq req, cusdk__BindPuRsp &rsp);

	/// Web service operation 'UnbindPu' (returns error code or SOAP_OK)
	virtual	int UnbindPu(cusdk__UnbindPuReq req, cusdk__UnbindPuRsp &rsp);

	/// Web service operation 'QueryRecordDays' (returns error code or SOAP_OK)
	virtual	int QueryRecordDays(cusdk__QueryRecordDaysReq req, cusdk__QueryRecordDaysRsp &rsp);

	/// Web service operation 'QueryRecord' (returns error code or SOAP_OK)
	virtual	int QueryRecord(cusdk__QueryRecordReq req, cusdk__QueryRecordRsp &rsp);

	/// Web service operation 'StartPlatformRecord' (returns error code or SOAP_OK)
	virtual	int StartPlatformRecord(cusdk__StartPlatformRecordReq req, cusdk__StartPlatformRecordRsp &rsp);

	/// Web service operation 'StopPlatformRecord' (returns error code or SOAP_OK)
	virtual	int StopPlatformRecord(cusdk__StopPlatformRecordReq req, cusdk__StopPlatformRecordRsp &rsp);

	/// Web service operation 'StartPuRecord' (returns error code or SOAP_OK)
	virtual	int StartPuRecord(cusdk__StartPuRecordReq req, cusdk__StartPuRecordRsp &rsp);

	/// Web service operation 'StopPuRecord' (returns error code or SOAP_OK)
	virtual	int StopPuRecord(cusdk__StopPuRecordReq req, cusdk__StopPuRecordRsp &rsp);

	/// Web service operation 'SetupPlayRecord' (returns error code or SOAP_OK)
	virtual	int SetupPlayRecord(cusdk__SetupPlayRecordReq req, cusdk__SetupPlayRecordRsp &rsp);

	/// Web service operation 'PlayRecord' (returns error code or SOAP_OK)
	virtual	int PlayRecord(cusdk__PlayRecordReq req, cusdk__PlayRecordRsp &rsp);

	/// Web service operation 'VcrCtrl' (returns error code or SOAP_OK)
	virtual	int VcrCtrl(cusdk__VcrCtrlReq req, cusdk__VcrCtrlRsp &rsp);

	/// Web service operation 'GetCurRecordPlayPosition' (returns error code or SOAP_OK)
	virtual	int GetCurRecordPlayPosition(cusdk__GetCurRecordPlayPositionReq req, cusdk__GetCurRecordPlayPositionRsp &rsp);

	/// Web service operation 'StopPlayRecord' (returns error code or SOAP_OK)
	virtual	int StopPlayRecord(cusdk__StopPlayRecordReq req, cusdk__StopPlayRecordRsp &rsp);

	/// Web service operation 'SetupDownloadRecord' (returns error code or SOAP_OK)
	virtual	int SetupDownloadRecord(cusdk__SetupDownloadRecordReq req, cusdk__SetupDownloadRecordRsp &rsp);

	/// Web service operation 'StartDownloadRecord' (returns error code or SOAP_OK)
	virtual	int StartDownloadRecord(cusdk__StartDownloadRecordReq req, cusdk__StartDownloadRecordRsp &rsp);

	/// Web service operation 'StopDownloadRecord' (returns error code or SOAP_OK)
	virtual	int StopDownloadRecord(cusdk__StopDownloadRecordReq req, cusdk__StopDownloadRecordRsp &rsp);

	/// Web service operation 'GetRecordPlan' (returns error code or SOAP_OK)
	virtual	int GetRecordPlan(cusdk__GetRecordPlanReq req, cusdk__GetRecordPlanRsp &rsp);

	/// Web service operation 'SetRecordPlan' (returns error code or SOAP_OK)
	virtual	int SetRecordPlan(cusdk__SetRecordPlanReq req, cusdk__SetRecordPlanRsp &rsp);

	/// Web service operation 'GetAllTVWall' (returns error code or SOAP_OK)
	virtual	int GetAllTVWall(cusdk__GetAllTVWallReq req, cusdk__GetAllTVWallRsp &rsp);

	/// Web service operation 'GetTVWall' (returns error code or SOAP_OK)
	virtual	int GetTVWall(cusdk__GetTVWallReq req, cusdk__GetTVWallRsp &rsp);

	/// Web service operation 'CreateTVWall' (returns error code or SOAP_OK)
	virtual	int CreateTVWall(cusdk__CreateTVWallReq req, cusdk__CreateTVWallRsp &rsp);

	/// Web service operation 'DelTVWall' (returns error code or SOAP_OK)
	virtual	int DelTVWall(cusdk__DelTVWallReq req, cusdk__DelTVWallRsp &rsp);

	/// Web service operation 'ModifyTVWall' (returns error code or SOAP_OK)
	virtual	int ModifyTVWall(cusdk__ModifyTVWallReq req, cusdk__ModifyTVWallRsp &rsp);

	/// Web service operation 'TVWallStartPlay' (returns error code or SOAP_OK)
	virtual	int TVWallStartPlay(cusdk__TVWallStartPlayReq req, cusdk__TVWallStartPlayRsp &rsp);

	/// Web service operation 'TVWallStopPlay' (returns error code or SOAP_OK)
	virtual	int TVWallStopPlay(cusdk__TVWallStopPlayReq req, cusdk__TVWallStopPlayRsp &rsp);

	/// Web service operation 'TVWallWindowPollContrl' (returns error code or SOAP_OK)
	virtual	int TVWallWindowPollContrl(cusdk__TVWallWindowPollContrlReq req, cusdk__TVWallWindowPollContrlRsp &rsp);

	/// Web service operation 'TVWallSaveScheme' (returns error code or SOAP_OK)
	virtual	int TVWallSaveScheme(cusdk__TVWallSaveSchemeReq req, cusdk__TVWallSaveSchemeRsp &rsp);

	/// Web service operation 'TVWallDelScheme' (returns error code or SOAP_OK)
	virtual	int TVWallDelScheme(cusdk__TVWallDelSchemeReq req, cusdk__TVWallDelSchemeRsp &rsp);

	/// Web service operation 'TVWallLoadScheme' (returns error code or SOAP_OK)
	virtual	int TVWallLoadScheme(cusdk__TVWallLoadSchemeReq req, cusdk__TVWallLoadSchemeRsp &rsp);

	/// Web service operation 'TVWallQueryScheme' (returns error code or SOAP_OK)
	virtual	int TVWallQueryScheme(cusdk__TVWallQuerySchemeReq req, cusdk__TVWallQuerySchemeRsp &rsp);

	/// Web service operation 'TVWallSetSchemePoll' (returns error code or SOAP_OK)
	virtual	int TVWallSetSchemePoll(cusdk__TVWallSetSchemePollReq req, cusdk__TVWallSetSchemePollRsp &rsp);

	/// Web service operation 'TVWallGetSchemePoll' (returns error code or SOAP_OK)
	virtual	int TVWallGetSchemePoll(cusdk__TVWallGetSchemePollReq req, cusdk__TVWallGetSchemePollRsp &rsp);

	/// Web service operation 'TVWallSchemePollControl' (returns error code or SOAP_OK)
	virtual	int TVWallSchemePollControl(cusdk__TVWallSchemePollControlReq req, cusdk__TVWallSchemePollControlRsp &rsp);

	/// Web service operation 'SetTVDivNum' (returns error code or SOAP_OK)
	virtual	int SetTVDivNum(cusdk__SetTVDivNumReq req, cusdk__SetTVDivNumRsp &rsp);

	/// Web service operation 'PlayRecordOnTVWall' (returns error code or SOAP_OK)
	virtual	int PlayRecordOnTVWall(cusdk__PlayRecordOnTVWallReq req, cusdk__PlayRecordOnTVWallRsp &rsp);

	/// Web service operation 'StopPlayRecordOnTVWall' (returns error code or SOAP_OK)
	virtual	int StopPlayRecordOnTVWall(cusdk__StopPlayRecordOnTVWallReq req, cusdk__StopPlayRecordOnTVWallRsp &rsp);

	/// Web service operation 'GetSupportMapTypes' (returns error code or SOAP_OK)
	virtual	int GetSupportMapTypes(cusdk__GetSupportMapTypesReq req, cusdk__GetSupportMapTypesRsp &rsp);

	/// Web service operation 'GetMapImageUploadUrl' (returns error code or SOAP_OK)
	virtual	int GetMapImageUploadUrl(cusdk__GetMapImageUploadUrlReq req, cusdk__GetMapImageUploadUrlRsp &rsp);

	/// Web service operation 'CreateMap' (returns error code or SOAP_OK)
	virtual	int CreateMap(cusdk__CreateMapReq req, cusdk__CreateMapRsp &rsp);

	/// Web service operation 'ModifyMap' (returns error code or SOAP_OK)
	virtual	int ModifyMap(cusdk__ModifyMapReq req, cusdk__ModifyMapRsp &rsp);

	/// Web service operation 'DelMap' (returns error code or SOAP_OK)
	virtual	int DelMap(cusdk__DelMapReq req, cusdk__DelMapRsp &rsp);

	/// Web service operation 'QueryMap' (returns error code or SOAP_OK)
	virtual	int QueryMap(cusdk__QueryMapReq req, cusdk__QueryMapRsp &rsp);

	/// Web service operation 'QueryMapArea' (returns error code or SOAP_OK)
	virtual	int QueryMapArea(cusdk__QueryMapAreaReq req, cusdk__QueryMapAreaRsp &rsp);

	/// Web service operation 'CreateMapArea' (returns error code or SOAP_OK)
	virtual	int CreateMapArea(cusdk__CreateMapAreaReq req, cusdk__CreateMapAreaRsp &rsp);

	/// Web service operation 'ModifyMapArea' (returns error code or SOAP_OK)
	virtual	int ModifyMapArea(cusdk__ModifyMapAreaReq req, cusdk__ModifyMapAreaRsp &rsp);

	/// Web service operation 'CreateMapElement' (returns error code or SOAP_OK)
	virtual	int CreateMapElement(cusdk__CreateMapElementReq req, cusdk__CreateMapElementRsp &rsp);

	/// Web service operation 'ModifyMapElement' (returns error code or SOAP_OK)
	virtual	int ModifyMapElement(cusdk__ModifyMapElementReq req, cusdk__ModifyMapElementRsp &rsp);

	/// Web service operation 'DelMapElement' (returns error code or SOAP_OK)
	virtual	int DelMapElement(cusdk__DelMapElementReq req, cusdk__DelMapElementRsp &rsp);

	/// Web service operation 'QueryMapElement' (returns error code or SOAP_OK)
	virtual	int QueryMapElement(cusdk__QueryMapElementReq req, cusdk__QueryMapElementRsp &rsp);

	/// Web service operation 'SearchMapElement' (returns error code or SOAP_OK)
	virtual	int SearchMapElement(cusdk__SearchMapElementReq req, cusdk__SearchMapElementRsp &rsp);

	/// Web service operation 'GetMapElementImageUploadUrl' (returns error code or SOAP_OK)
	virtual	int GetMapElementImageUploadUrl(cusdk__GetMapElementImageUploadUrlReq req, cusdk__GetMapElementImageUploadUrlRsp &rsp);

	/// Web service operation 'QueryMapElementImageList' (returns error code or SOAP_OK)
	virtual	int QueryMapElementImageList(cusdk__QueryMapElementImageListReq req, cusdk__QueryMapElementImageListRsp &rsp);

	/// Web service operation 'MapPositionMar2Earth' (returns error code or SOAP_OK)
	virtual	int MapPositionMar2Earth(cusdk__MapPositionMar2EarthReq req, cusdk__MapPositionMar2EarthRsp &rsp);

	/// Web service operation 'MapPositionEarth2Mar' (returns error code or SOAP_OK)
	virtual	int MapPositionEarth2Mar(cusdk__MapPositionEarth2MarReq req, cusdk__MapPositionEarth2MarRsp &rsp);

	/// Web service operation 'GetEMapDataVersion' (returns error code or SOAP_OK)
	virtual	int GetEMapDataVersion(cusdk__GetEMapDataVersionReq req, cusdk__GetEMapDataVersionRsp &rsp);

	/// Web service operation 'GetAlarmLinkDataVersion' (returns error code or SOAP_OK)
	virtual	int GetAlarmLinkDataVersion(cusdk__GetAlarmLinkDataVersionReq req, cusdk__GetAlarmLinkDataVersionRsp &rsp);

	/// Web service operation 'QueryAlarmLinkConfig' (returns error code or SOAP_OK)
	virtual	int QueryAlarmLinkConfig(cusdk__QueryAlarmLinkConfigReq req, cusdk__QueryAlarmLinkConfigRsp &rsp);

	/// Web service operation 'GetAlarmLinkConfig' (returns error code or SOAP_OK)
	virtual	int GetAlarmLinkConfig(cusdk__GetAlarmLinkConfigReq req, cusdk__GetAlarmLinkConfigRsp &rsp);

	/// Web service operation 'SetAlarmLinkConfig' (returns error code or SOAP_OK)
	virtual	int SetAlarmLinkConfig(cusdk__SetAlarmLinkConfigReq req, cusdk__SetAlarmLinkConfigRsp &rsp);

	/// Web service operation 'QueryAlarmLinkArea' (returns error code or SOAP_OK)
	virtual	int QueryAlarmLinkArea(cusdk__QueryAlarmLinkAreaReq req, cusdk__QueryAlarmLinkAreaRsp &rsp);

	/// Web service operation 'CreateAlarmLinkArea' (returns error code or SOAP_OK)
	virtual	int CreateAlarmLinkArea(cusdk__CreateAlarmLinkAreaReq req, cusdk__CreateAlarmLinkAreaRsp &rsp);

	/// Web service operation 'DelAlarmLinkArea' (returns error code or SOAP_OK)
	virtual	int DelAlarmLinkArea(cusdk__DelAlarmLinkAreaReq req, cusdk__DelAlarmLinkAreaRsp &rsp);

	/// Web service operation 'ModifyAlarmLinkArea' (returns error code or SOAP_OK)
	virtual	int ModifyAlarmLinkArea(cusdk__ModifyAlarmLinkAreaReq req, cusdk__ModifyAlarmLinkAreaRsp &rsp);

	/// Web service operation 'QueryUserLog' (returns error code or SOAP_OK)
	virtual	int QueryUserLog(cusdk__QueryUserLogReq req, cusdk__QueryUserLogRsp &rsp);

	/// Web service operation 'StartExportUserLog' (returns error code or SOAP_OK)
	virtual	int StartExportUserLog(cusdk__StartExportUserLogReq req, cusdk__StartExportUserLogRsp &rsp);

	/// Web service operation 'GetExportUserLogProcess' (returns error code or SOAP_OK)
	virtual	int GetExportUserLogProcess(cusdk__GetExportUserLogProcessReq req, cusdk__GetExportUserLogProcessRsp &rsp);

	/// Web service operation 'StopExportUserLog' (returns error code or SOAP_OK)
	virtual	int StopExportUserLog(cusdk__StopExportUserLogReq req, cusdk__StopExportUserLogRsp &rsp);

	/// Web service operation 'QueryDeviceLog' (returns error code or SOAP_OK)
	virtual	int QueryDeviceLog(cusdk__QueryDeviceLogReq req, cusdk__QueryDeviceLogRsp &rsp);

	/// Web service operation 'StartExportDeviceLog' (returns error code or SOAP_OK)
	virtual	int StartExportDeviceLog(cusdk__StartExportDeviceLogReq req, cusdk__StartExportDeviceLogRsp &rsp);

	/// Web service operation 'GetExportDeviceLogProcess' (returns error code or SOAP_OK)
	virtual	int GetExportDeviceLogProcess(cusdk__GetExportDeviceLogProcessReq req, cusdk__GetExportDeviceLogProcessRsp &rsp);

	/// Web service operation 'StopExportDeviceLog' (returns error code or SOAP_OK)
	virtual	int StopExportDeviceLog(cusdk__StopExportDeviceLogReq req, cusdk__StopExportDeviceLogRsp &rsp);

	/// Web service operation 'QueryAlarmLog' (returns error code or SOAP_OK)
	virtual	int QueryAlarmLog(cusdk__QueryAlarmLogReq req, cusdk__QueryAlarmLogRsp &rsp);

	/// Web service operation 'StartExportAlarmLog' (returns error code or SOAP_OK)
	virtual	int StartExportAlarmLog(cusdk__StartExportAlarmLogReq req, cusdk__StartExportAlarmLogRsp &rsp);

	/// Web service operation 'GetExportAlarmLogProcess' (returns error code or SOAP_OK)
	virtual	int GetExportAlarmLogProcess(cusdk__GetExportAlarmLogProcessReq req, cusdk__GetExportAlarmLogProcessRsp &rsp);

	/// Web service operation 'StopExportAlarmLog' (returns error code or SOAP_OK)
	virtual	int StopExportAlarmLog(cusdk__StopExportAlarmLogReq req, cusdk__StopExportAlarmLogRsp &rsp);

	/// Web service operation 'GetLogConfig' (returns error code or SOAP_OK)
	virtual	int GetLogConfig(cusdk__GetLogConfigReq req, cusdk__GetLogConfigRsp &rsp);

	/// Web service operation 'SetLogConfig' (returns error code or SOAP_OK)
	virtual	int SetLogConfig(cusdk__SetLogConfigReq req, cusdk__SetLogConfigRsp &rsp);

	/// Web service operation 'CallPu' (returns error code or SOAP_OK)
	virtual	int CallPu(cusdk__CallPuReq req, cusdk__CallPuRsp &rsp);

	/// Web service operation 'HangUpPu' (returns error code or SOAP_OK)
	virtual	int HangUpPu(cusdk__HangUpPuReq req, cusdk__HangUpPuRsp &rsp);

	/// Web service operation 'GetDeviceEncoderParam' (returns error code or SOAP_OK)
	virtual	int GetDeviceEncoderParam(cusdk__GetDeviceEncoderParamReq req, cusdk__GetDeviceEncoderParamRsp &rsp);

	/// Web service operation 'GetDeviceAudioEncoderParam' (returns error code or SOAP_OK)
	virtual	int GetDeviceAudioEncoderParam(cusdk__GetDeviceAudioEncoderParamReq req, cusdk__GetDeviceAudioEncoderParamRsp &rsp);

	/// Web service operation 'SetDeviceEncoderParam' (returns error code or SOAP_OK)
	virtual	int SetDeviceEncoderParam(cusdk__SetDeviceEncoderParamReq req, cusdk__SetDeviceEncoderParamRsp &rsp);

	/// Web service operation 'SetPuVidSrcOSD' (returns error code or SOAP_OK)
	virtual	int SetPuVidSrcOSD(cusdk__SetPuVidSrcOSDReq req, cusdk__SetPuVidSrcOSDRsp &rsp);

	/// Web service operation 'GetPuVidSrcOSD' (returns error code or SOAP_OK)
	virtual	int GetPuVidSrcOSD(cusdk__GetPuVidSrcOSDReq req, cusdk__GetPuVidSrcOSDRsp &rsp);

	/// Web service operation 'SetDeviceName' (returns error code or SOAP_OK)
	virtual	int SetDeviceName(cusdk__SetDeviceNameReq req, cusdk__SetDeviceNameRsp &rsp);

	/// Web service operation 'GetCameraProtocolType' (returns error code or SOAP_OK)
	virtual	int GetCameraProtocolType(cusdk__GetCameraProtocolTypeReq req, cusdk__GetCameraProtocolTypeRsp &rsp);

	/// Web service operation 'SetCameraProtocolType' (returns error code or SOAP_OK)
	virtual	int SetCameraProtocolType(cusdk__SetCameraProtocolTypeReq req, cusdk__SetCameraProtocolTypeRsp &rsp);

	/// Web service operation 'GetMotionDetectConfig' (returns error code or SOAP_OK)
	virtual	int GetMotionDetectConfig(cusdk__GetMotionDetectConfigReq req, cusdk__GetMotionDetectConfigRsp &rsp);

	/// Web service operation 'SetMotionDetectConfig' (returns error code or SOAP_OK)
	virtual	int SetMotionDetectConfig(cusdk__SetMotionDetectConfigReq req, cusdk__SetMotionDetectConfigRsp &rsp);

	/// Web service operation 'GetShadeConfig' (returns error code or SOAP_OK)
	virtual	int GetShadeConfig(cusdk__GetShadeConfigReq req, cusdk__GetShadeConfigRsp &rsp);

	/// Web service operation 'SetShadeConfig' (returns error code or SOAP_OK)
	virtual	int SetShadeConfig(cusdk__SetShadeConfigReq req, cusdk__SetShadeConfigRsp &rsp);

	/// Web service operation 'GetDeviceChannelName' (returns error code or SOAP_OK)
	virtual	int GetDeviceChannelName(cusdk__GetDeviceChannelNameReq req, cusdk__GetDeviceChannelNameRsp &rsp);

	/// Web service operation 'SetDeviceChannelName' (returns error code or SOAP_OK)
	virtual	int SetDeviceChannelName(cusdk__SetDeviceChannelNameReq req, cusdk__SetDeviceChannelNameRsp &rsp);

	/// Web service operation 'GetSyncVideoSrcNameEnable' (returns error code or SOAP_OK)
	virtual	int GetSyncVideoSrcNameEnable(cusdk__GetSyncVideoSrcNameEnableReq req, cusdk__GetSyncVideoSrcNameEnableRsp &rsp);

	/// Web service operation 'SetSyncVideoSrcNameEnable' (returns error code or SOAP_OK)
	virtual	int SetSyncVideoSrcNameEnable(cusdk__SetSyncVideoSrcNameEnableReq req, cusdk__SetSyncVideoSrcNameEnableRsp &rsp);

	/// Web service operation 'GetPtzPresetName' (returns error code or SOAP_OK)
	virtual	int GetPtzPresetName(cusdk__GetPtzPresetNameReq req, cusdk__GetPtzPresetNameRsp &rsp);

	/// Web service operation 'SetPtzPresetName' (returns error code or SOAP_OK)
	virtual	int SetPtzPresetName(cusdk__SetPtzPresetNameReq req, cusdk__SetPtzPresetNameRsp &rsp);

	/// Web service operation 'DelPtzPresetName' (returns error code or SOAP_OK)
	virtual	int DelPtzPresetName(cusdk__DelPtzPresetNameReq req, cusdk__DelPtzPresetNameRsp &rsp);

	/// Web service operation 'VsipChannelData' (returns error code or SOAP_OK)
	virtual	int VsipChannelData(cusdk__VsipChannelDataReq req, cusdk__VsipChannelDataRsp &rsp);

	/// Web service operation 'SetTransDataParam' (returns error code or SOAP_OK)
	virtual	int SetTransDataParam(cusdk__SetTransDataParamReq req, cusdk__SetTransDataParamRsp &rsp);

	/// Web service operation 'GetTransDataParam' (returns error code or SOAP_OK)
	virtual	int GetTransDataParam(cusdk__GetTransDataParamReq req, cusdk__GetTransDataParamRsp &rsp);

	/// Web service operation 'QueryGPSTrace' (returns error code or SOAP_OK)
	virtual	int QueryGPSTrace(cusdk__QueryGPSTraceReq req, cusdk__QueryGPSTraceRsp &rsp);

	/// Web service operation 'GetMapConfig' (returns error code or SOAP_OK)
	virtual	int GetMapConfig(cusdk__GetMapConfigReq req, cusdk__GetMapConfigRsp &rsp);

	/// Web service operation 'SetMapConfig' (returns error code or SOAP_OK)
	virtual	int SetMapConfig(cusdk__SetMapConfigReq req, cusdk__SetMapConfigRsp &rsp);

	/// Web service operation 'GetDeviceSerialConfig' (returns error code or SOAP_OK)
	virtual	int GetDeviceSerialConfig(cusdk__GetDeviceSerialConfigReq req, cusdk__GetDeviceSerialConfigRsp &rsp);

	/// Web service operation 'SetDeviceSerialConfig' (returns error code or SOAP_OK)
	virtual	int SetDeviceSerialConfig(cusdk__SetDeviceSerialConfigReq req, cusdk__SetDeviceSerialConfigRsp &rsp);

	/// Web service operation 'GetDeviceGBID' (returns error code or SOAP_OK)
	virtual	int GetDeviceGBID(cusdk__GetDeviceGBIDReq req, cusdk__GetDeviceGBIDRsp &rsp);

	/// Web service operation 'GetCivilcode' (returns error code or SOAP_OK)
	virtual	int GetCivilcode(cusdk__GetCivilcodeReq req, cusdk__GetCivilcodeRsp &rsp);

	/// Web service operation 'GetDeviceChnByGBID' (returns error code or SOAP_OK)
	virtual	int GetDeviceChnByGBID(cusdk__GetDeviceChnByGBIDReq req, cusdk__GetDeviceChnByGBIDRsp &rsp);

	/// Web service operation 'GetCAPSConfig' (returns error code or SOAP_OK)
	virtual	int GetCAPSConfig(cusdk__GetCAPSConfigReq req, cusdk__GetCAPSConfigRsp &rsp);

	/// Web service operation 'SetCAPSConfig' (returns error code or SOAP_OK)
	virtual	int SetCAPSConfig(cusdk__SetCAPSConfigReq req, cusdk__SetCAPSConfigRsp &rsp);

	/// Web service operation 'QueryCAPSDeviceList' (returns error code or SOAP_OK)
	virtual	int QueryCAPSDeviceList(cusdk__QueryCAPSDeviceListReq req, cusdk__QueryCAPSDeviceListRsp &rsp);

	/// Web service operation 'CAPSAddDevice' (returns error code or SOAP_OK)
	virtual	int CAPSAddDevice(cusdk__CAPSAddDeviceReq req, cusdk__CAPSAddDeviceRsp &rsp);

	/// Web service operation 'CAPSModifyDevice' (returns error code or SOAP_OK)
	virtual	int CAPSModifyDevice(cusdk__CAPSModifyDeviceReq req, cusdk__CAPSModifyDeviceRsp &rsp);

	/// Web service operation 'CAPSDelDevice' (returns error code or SOAP_OK)
	virtual	int CAPSDelDevice(cusdk__CAPSDelDeviceReq req, cusdk__CAPSDelDeviceRsp &rsp);

	/// Web service operation 'GetOfflineDeviceStat' (returns error code or SOAP_OK)
	virtual	int GetOfflineDeviceStat(cusdk__GetOfflineDeviceStatReq req, cusdk__GetOfflineDeviceStatRsp &rsp);

	/// Web service operation 'UpdateCUProperty' (returns error code or SOAP_OK)
	virtual	int UpdateCUProperty(cusdk__UpdateCUPropertyReq req, cusdk__UpdateCUPropertyRsp &rsp);

	/// Web service operation 'RestartDevice' (returns error code or SOAP_OK)
	virtual	int RestartDevice(cusdk__RestartDeviceReq req, cusdk__RestartDeviceRsp &rsp);

	/// Web service operation 'UserAddDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserAddDeviceGroup(cusdk__UserAddDeviceGroupReq req, cusdk__UserAddDeviceGroupRsp &rsp);

	/// Web service operation 'UserDelDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserDelDeviceGroup(cusdk__UserDelDeviceGroupReq req, cusdk__UserDelDeviceGroupRsp &rsp);

	/// Web service operation 'UserGroupAddDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserGroupAddDeviceGroup(cusdk__UserGroupAddDeviceGroupReq req, cusdk__UserGroupAddDeviceGroupRsp &rsp);

	/// Web service operation 'UserGroupDelDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserGroupDelDeviceGroup(cusdk__UserGroupDelDeviceGroupReq req, cusdk__UserGroupDelDeviceGroupRsp &rsp);

	/// Web service operation 'UserSetAutoSyncDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserSetAutoSyncDeviceGroup(cusdk__UserSetAutoSyncDeviceGroupReq req, cusdk__UserSetAutoSyncDeviceGroupRsp &rsp);

	/// Web service operation 'UserGroupSetAutoSyncDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserGroupSetAutoSyncDeviceGroup(cusdk__UserGroupSetAutoSyncDeviceGroupReq req, cusdk__UserGroupSetAutoSyncDeviceGroupRsp &rsp);

	/// Web service operation 'QueryOperationProgress' (returns error code or SOAP_OK)
	virtual	int QueryOperationProgress(cusdk__QueryOperationProgreeReq req, cusdk__QueryOperationProgreeRsp &rsp);

	/// Web service operation 'UserQueryAutoSyncDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserQueryAutoSyncDeviceGroup(cusdk__UserQueryAutoSyncDeviceGroupReq req, cusdk__UserQueryAutoSyncDeviceGroupRsp &rsp);

	/// Web service operation 'UserGroupQueryAutoSyncDeviceGroup' (returns error code or SOAP_OK)
	virtual	int UserGroupQueryAutoSyncDeviceGroup(cusdk__UserGroupQueryAutoSyncDeviceGroupReq req, cusdk__UserGroupQueryAutoSyncDeviceGroupRsp &rsp);

	/// Web service operation 'GetSuperGBDomainList' (returns error code or SOAP_OK)
	virtual	int GetSuperGBDomainList(cusdk__GetGBDomainListReq req, cusdk__GetGBDomainListRsp &rsp);

	/// Web service operation 'PushDevice' (returns error code or SOAP_OK)
	virtual	int PushDevice(cusdk__DevicePushReq req, cusdk__DevicePushRsp &rsp);

	/// Web service operation 'GetDataVersion' (returns error code or SOAP_OK)
	virtual	int GetDataVersion(cusdk__GetDataVersionReq req, cusdk__GetDataVersionRsp &rsp);

	/// Web service operation 'StartDataFileExport' (returns error code or SOAP_OK)
	virtual	int StartDataFileExport(cusdk__StartDataFileExportReq req, cusdk__StartDataFileExportRsp &rsp);

	/// Web service operation 'EndDataFileExport' (returns error code or SOAP_OK)
	virtual	int EndDataFileExport(cusdk__EndDataFileExportReq req, cusdk__EndDataFileExportRsp &rsp);

	/// Web service operation 'StartDataFileImport' (returns error code or SOAP_OK)
	virtual	int StartDataFileImport(cusdk__StartDataFileImportReq req, cusdk__StartDataFileImportRsp &rsp);

	/// Web service operation 'EndDataFileImport' (returns error code or SOAP_OK)
	virtual	int EndDataFileImport(cusdk__EndDataFileImportReq req, cusdk__EndDataFileImportRsp &rsp);

	/// Web service operation 'GetOperationProgress' (returns error code or SOAP_OK)
	virtual	int GetOperationProgress(cusdk__GetOperationProgreeReq req, cusdk__GetOperationProgreeRsp &rsp);

	/// Web service operation 'GetChildrenGBDomainList' (returns error code or SOAP_OK)
	virtual	int GetChildrenGBDomainList(cusdk__GetChildrenGBDomainListReq req, cusdk__GetChildrenGBDomainListRsp &rsp);

	/// Web service operation 'GetGBDevciePushDomain' (returns error code or SOAP_OK)
	virtual	int GetGBDevciePushDomain(cusdk__GetGBDevicePushDomainReq req, cusdk__GetGBDevicePushDomainRsp &rsp);

	/// Web service operation 'UpdateOperationProgress' (returns error code or SOAP_OK)
	virtual	int UpdateOperationProgress(cusdk__UpdateOperationProgreeReq req, cusdk__UpdateOperationProgreeRsp &rsp);

	/// Web service operation 'GetResInfo' (returns error code or SOAP_OK)
	virtual	int GetResInfo(cusdk__ResInfoReq cResInfoReq, cusdk__ResInfoRsp &cResInfoRsp);

	/// Web service operation 'SearchDevice' (returns error code or SOAP_OK)
	virtual	int SearchDevice(cusdk__SearchDeviceReq req, cusdk__SearchDeviceRsp &rsp);

	/// Web service operation 'GetSearchResult' (returns error code or SOAP_OK)
	virtual	int GetSearchResult(cusdk__GetSearchResultReq req, cusdk__GetSearchResultRsp &rsp);

	/// Web service operation 'GetSearchResultByGroup' (returns error code or SOAP_OK)
	virtual	int GetSearchResultByGroup(cusdk__GetSearchResultByGroupReq req, cusdk__GetSearchResultByGroupRsp &rsp);

	/// Web service operation 'EndOperation' (returns error code or SOAP_OK)
	virtual	int EndOperation(cusdk__EndOperationReq req, cusdk__EndOperationRsp &rsp);

	/// Web service operation 'GetDeviceGroup' (returns error code or SOAP_OK)
	virtual	int GetDeviceGroup(cusdk__GetDeviceGroupReq req, cusdk__GetDeviceGroupRsp &rsp);

	/// Web service operation 'GetDevice' (returns error code or SOAP_OK)
	virtual	int GetDevice(cusdk__GetDeviceReq req, cusdk__GetDeviceRsp &rsp);

	/// Web service operation 'GetDeviceGroupPath' (returns error code or SOAP_OK)
	virtual	int GetDeviceGroupPath(cusdk__GetDeviceGroupPathReq req, cusdk__GetDeviceGroupPathRsp &rsp);

	/// Web service operation 'CreateCustomTreeView' (returns error code or SOAP_OK)
	virtual	int CreateCustomTreeView(cusdk__CreateCustomTreeViewReq req, cusdk__CreateCustomTreeViewRsp &rsp);

	/// Web service operation 'ModifyCustomTreeViewName' (returns error code or SOAP_OK)
	virtual	int ModifyCustomTreeViewName(cusdk__ModifyCustomTreeViewNameReq req, cusdk__ModifyCustomTreeViewNameRsp &rsp);

	/// Web service operation 'DeleteCustomTreeView' (returns error code or SOAP_OK)
	virtual	int DeleteCustomTreeView(cusdk__DeleteCustomTreeViewReq req, cusdk__DeleteCustomTreeViewRsp &rsp);

	/// Web service operation 'GetCustomTreeViewList' (returns error code or SOAP_OK)
	virtual	int GetCustomTreeViewList(cusdk__GetCustomTreeViewListReq req, cusdk__GetCustomTreeViewListRsp &rsp);

	/// Web service operation 'GetUserDeviceInGroup' (returns error code or SOAP_OK)
	virtual	int GetUserDeviceInGroup(cusdk__GetUserDeviceInGroupReq req, cusdk__GetUserDeviceInGroupRsp &rsp);

	/// Web service operation 'BatchOperation' (returns error code or SOAP_OK)
	virtual	int BatchOperation(cusdk__BatchOperationReq req, cusdk__BatchOperationRsp &rsp);

	/// Web service operation 'GetDeviceGroupVideoSrcNum' (returns error code or SOAP_OK)
	virtual	int GetDeviceGroupVideoSrcNum(cusdk__GetDeviceGroupVideoSrcNumReq req, cusdk__GetDeviceGroupVideoSrcNumRsp &rsp);

	/// Web service operation 'GetVSOfflineInfo' (returns error code or SOAP_OK)
	virtual	int GetVSOfflineInfo(cusdk__GetVSOfflineInfoReq req, cusdk__GetVSOfflineInfoRsp &rsp);

	/// Web service operation 'GetDevAzimuthalAngle' (returns error code or SOAP_OK)
	virtual	int GetDevAzimuthalAngle(cusdk__GetDevAzimuthalAngleReq req, cusdk__GetDevAzimuthalAngleRsp &rsp);

	/// Web service operation 'DeleteRecord' (returns error code or SOAP_OK)
	virtual	int DeleteRecord(cusdk__DeleteRecordReq req, cusdk__DeleteRecordRsp &rsp);

	/// Web service operation 'AutoMatchGBId' (returns error code or SOAP_OK)
	virtual	int AutoMatchGBId(cusdk__AutoMatchGBIdReq req, cusdk__AutoMatchGBIdRsp &rsp);

	/// Web service operation 'GetGroupDevSumNum' (returns error code or SOAP_OK)
	virtual	int GetGroupDevSumNum(cusdk__GetGroupDevSumNumReq req, cusdk__GetGroupDevSumNumRsp &rsp);

	/// Web service operation 'ModifyGBDeviceGroup' (returns error code or SOAP_OK)
	virtual	int ModifyGBDeviceGroup(cusdk__ModifyGBDeviceGroupReq req, cusdk__ModifyGBDeviceGroupRsp &rsp);

	/// Web service operation 'ModifyGBDevice' (returns error code or SOAP_OK)
	virtual	int ModifyGBDevice(cusdk__ModifyGBDeviceReq req, cusdk__ModifyGBDeviceRsp &rsp);

	/// Web service operation 'StartDevicePush' (returns error code or SOAP_OK)
	virtual	int StartDevicePush(cusdk__StartDevicePushReq req, cusdk__StartDevicePushRsp &rsp);

	/// Web service operation 'GetGBDeviceByGroup' (returns error code or SOAP_OK)
	virtual	int GetGBDeviceByGroup(cusdk__GetGBDeviceByGroupReq req, cusdk__GetGBDeviceByGroupRsp &rsp);

	/// Web service operation 'SearchGBDevice' (returns error code or SOAP_OK)
	virtual	int SearchGBDevice(cusdk__SearchGBDeviceReq req, cusdk__SearchGBDeviceRsp &rsp);

	/// Web service operation 'SearchGBDeviceGroup' (returns error code or SOAP_OK)
	virtual	int SearchGBDeviceGroup(cusdk__SearchGBDeviceGroupReq req, cusdk__SearchGBDeviceGroupRsp &rsp);

	/// Web service operation 'GetNextDeviceGBIDError' (returns error code or SOAP_OK)
	virtual	int GetNextDeviceGBIDError(cusdk__GetNextDeviceGBIDErrorReq req, cusdk__GetNextDeviceGBIDErrorRsp &rsp);

	/// Web service operation 'GetServerConfig' (returns error code or SOAP_OK)
	virtual	int GetServerConfig(cusdk__GetServerConfigReq req, cusdk__GetServerConfigRsp &rsp);

	/// Web service operation 'SetServerConfig' (returns error code or SOAP_OK)
	virtual	int SetServerConfig(cusdk__SetServerConfigReq req, cusdk__SetServerConfigRsp &rsp);

	/// Web service operation 'TVWallClearAlarm' (returns error code or SOAP_OK)
	virtual	int TVWallClearAlarm(cusdk__TVWallClearAlarmReq req, cusdk__TVWallClearAlarmRsp &rsp);

	/// Web service operation 'LockRecord' (returns error code or SOAP_OK)
	virtual	int LockRecord(cusdk__LockRecordReq req, cusdk__LockRecordRsp &rsp);

	/// Web service operation 'UnlockRecord' (returns error code or SOAP_OK)
	virtual	int UnlockRecord(cusdk__UnlockRecordReq req, cusdk__UnlockRecordRsp &rsp);

	/// Web service operation 'GetPULongOSD' (returns error code or SOAP_OK)
	virtual	int GetPULongOSD(cusdk__GetPULongOSDReq req, cusdk__GetPULongOSDRsp &rsp);

	/// Web service operation 'SetPULongOSD' (returns error code or SOAP_OK)
	virtual	int SetPULongOSD(cusdk__SetPULongOSDReq req, cusdk__SetPULongOSDRsp &rsp);

	/// Web service operation 'GetDeviceCertificate' (returns error code or SOAP_OK)
	virtual	int GetDeviceCertificate(cusdk__GetDeviceCertificateReq req, cusdk__GetDeviceCertificateRsp &rsp);

	/// Web service operation 'DeviceSignatrueCtrl' (returns error code or SOAP_OK)
	virtual	int DeviceSignatrueCtrl(cusdk__DeviceSignatrueCtrlReq req, cusdk__DeviceSignatrueCtrlRsp &rsp);

	/// Web service operation 'DeviceEncryptionCtrl' (returns error code or SOAP_OK)
	virtual	int DeviceEncryptionCtrl(cusdk__DeviceEncryptionCtrlReq req, cusdk__DeviceEncryptionCtrlRsp &rsp);

	/// Web service operation 'BidirectionalAuth1' (returns error code or SOAP_OK)
	virtual	int BidirectionalAuth1(cusdk__BidirectionalAuth1Req req, cusdk__BidirectionalAuth1Rsp &rsp);

	/// Web service operation 'BidirectionalAuth2' (returns error code or SOAP_OK)
	virtual	int BidirectionalAuth2(cusdk__BidirectionalAuth2Req req, cusdk__BidirectionalAuth2Rsp &rsp);

	/// Web service operation 'AdjustVideoSrcOrder' (returns error code or SOAP_OK)
	virtual	int AdjustVideoSrcOrder(cusdk__AdjustVideoSrcOrderReq req, cusdk__AdjustVideoSrcOrderRsp &rsp);

	/// Web service operation 'GetAlarmTypes' (returns error code or SOAP_OK)
	virtual	int GetAlarmTypes(cusdk__GetAlarmTypesReq req, cusdk__GetAlarmTypesRsp &rsp);

	/// Web service operation 'EliminateAlarm' (returns error code or SOAP_OK)
	virtual	int EliminateAlarm(cusdk__EliminateAlarmReq req, cusdk__EliminateAlarmRsp &rsp);

	/// Web service operation 'GetDeviceRecordsServerUrl' (returns error code or SOAP_OK)
	virtual	int GetDeviceRecordsServerUrl(cusdk__GetDeviceRecordsServerUrlReq req, cusdk__GetDeviceRecordsServerUrlRsp &rsp);

	/// Web service operation 'LockRecordBatch' (returns error code or SOAP_OK)
	virtual	int LockRecordBatch(cusdk__LockRecordBatchReq req, cusdk__LockRecordBatchRsp &rsp);

	/// Web service operation 'UnlockRecordBatch' (returns error code or SOAP_OK)
	virtual	int UnlockRecordBatch(cusdk__UnlockRecordBatchReq req, cusdk__UnlockRecordBatchRsp &rsp);

	/// Web service operation 'QueryLockedRecord' (returns error code or SOAP_OK)
	virtual	int QueryLockedRecord(cusdk__QueryLockedRecordReq req, cusdk__QueryLockedRecordRsp &rsp);

	/// Web service operation 'GetStreamPreDispatchConfig' (returns error code or SOAP_OK)
	virtual	int GetStreamPreDispatchConfig(cusdk__GetStreamPreDispatchConfigReq req, cusdk__GetStreamPreDispatchConfigRsp &rsp);

	/// Web service operation 'SetStreamPreDispatchConfig' (returns error code or SOAP_OK)
	virtual	int SetStreamPreDispatchConfig(cusdk__SetStreamPreDispatchConfigReq req, cusdk__SetStreamPreDispatchConfigRsp &rsp);

	/// Web service operation 'QueryStreamPreDispatchDevice' (returns error code or SOAP_OK)
	virtual	int QueryStreamPreDispatchDevice(cusdk__QueryStreamPreDispatchDeviceReq req, cusdk__QueryStreamPreDispatchDeviceRsp &rsp);

	/// Web service operation 'StreamPreDispatchAddDevice' (returns error code or SOAP_OK)
	virtual	int StreamPreDispatchAddDevice(cusdk__StreamPreDispatchAddDeviceReq req, cusdk__StreamPreDispatchAddDeviceRsp &rsp);

	/// Web service operation 'StreamPreDispatchDelDevice' (returns error code or SOAP_OK)
	virtual	int StreamPreDispatchDelDevice(cusdk__StreamPreDispatchDelDeviceReq req, cusdk__StreamPreDispatchDelDeviceRsp &rsp);

	/// Web service operation 'GetEncChnRes' (returns error code or SOAP_OK)
	virtual	int GetEncChnRes(cusdk__GetEncChnResReq req, cusdk__GetEncChnResRsp &rsp);

	/// Web service operation 'AllocEncChnRes' (returns error code or SOAP_OK)
	virtual	int AllocEncChnRes(cusdk__AllocEncChnResReq req, cusdk__AllocEncChnResRsp &rsp);

	/// Web service operation 'ReleaseEncChnRes' (returns error code or SOAP_OK)
	virtual	int ReleaseEncChnRes(cusdk__ReleaseEncChnResReq req, cusdk__ReleaseEncChnResRsp &rsp);

	/// Web service operation 'GBPuTransdataSsSet' (returns error code or SOAP_OK)
	virtual	int GBPuTransdataSsSet(cusdk__GBPuTransdataSsSetReq req, cusdk__GBPuTransdataSsSetRsp &rsp);

	/// Web service operation 'GetGBDomainPrivilege' (returns error code or SOAP_OK)
	virtual	int GetGBDomainPrivilege(cusdk__GetGBDomainPrivilegeReq req, cusdk__GetGBDomainPrivilegeRsp &rsp);

	/// Web service operation 'SetGBDomainPrivilege' (returns error code or SOAP_OK)
	virtual	int SetGBDomainPrivilege(cusdk__SetGBDomainPrivilegeReq req, cusdk__SetGBDomainPrivilegeRsp &rsp);

	/// Web service operation 'GetGBConfig' (returns error code or SOAP_OK)
	virtual	int GetGBConfig(cusdk__GetGBConfigReq req, cusdk__GetGBConfigRsp &rsp);

	/// Web service operation 'SetGBConfig' (returns error code or SOAP_OK)
	virtual	int SetGBConfig(cusdk__SetGBConfigReq req, cusdk__SetGBConfigRsp &rsp);

	/// Web service operation 'SetCertificate' (returns error code or SOAP_OK)
	virtual	int SetCertificate(cusdk__SetCertificateReq req, cusdk__SetCertificateRsp &rsp);

	/// Web service operation 'GetCertificate' (returns error code or SOAP_OK)
	virtual	int GetCertificate(cusdk__GetCertificateReq req, cusdk__GetCertificateRsp &rsp);
};
#endif
